const TrainersLookup() = () => {
	private static objMap = (obj, process, shouldProcess) => {
		return Object.fromEntries(
			Object.entries(obj).map(([k, v]) => 
				[k, (v === Object(v) && !Array.isArray(v) && shouldProcess(k, v)) ? this.objMap(v, process, shouldProcess) : process(k, v)]
			)
		);
	}
	
	private static trainersLookupKV = {
		"": { 
			name: "",
			class: "",
			//image: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D",
			image: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D",
			reference: "https://stackoverflow.com/a/19126281",
			teams: {
				"": { name: "" },
				"0": { name: "" },
			}
		}, // undefined / default value. 
		"0": { 
			name: "",
			class: "",
			//image: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D",
			image: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D",
			reference: "https://stackoverflow.com/a/19126281",
			teams: {
				"": { name: "" }
				"0": { name: "" },
			}
		}, // undefined / default value. 
		"1": { 
			name: "YOUNGSTER",
			class: "Youngster",
			//image: "https://archives.bulbagarden.net/media/upload/d/d5/Spr_FRLG_Youngster.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Youngster.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Youngster.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "BEN" },
				"2": { name: "CALVIN" },
				"3": { name: "JOSH" },
				"4": { name: "TIMMY" },
				"5": { name: "JOEY" },
				"6": { name: "DAN" },
				"7": { name: "CHAD" },
				"8": { name: "TYLER" },
				"9": { name: "EDDIE" },
				"10": { name: "DILLON" },
				"11": { name: "YASU" },
				"12": { name: "DAVE" },
				"13": { name: "" },
				"14": { name: "A.J." },
			}
		},
		"2": { 
			name: "BUG CATCHER",
			class: "BugCatcher",
			//image: "https://archives.bulbagarden.net/media/upload/b/b9/Spr_FRLG_Bug_Catcher.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Bug_Catcher.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Bug_Catcher.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "ANTHONY" },
				"2": { name: "CHARLIE" },
				"3": { name: "SAMMY" },
				"4": { name: "COLTON" },
				"5": { name: "GREG" },
				"6": { name: "JAMES" },
				"7": { name: "KENT" },
				"8": { name: "ROBBY" },
				"9": { name: "CALE" },
				"10": { name: "KEIGO" },
				"11": { name: "ELIJAH" },
				"12": { name: "" },
				"13": { name: "BRENT" },
				"14": { name: "CONNER" },
				"15": { name: "SAMURAI" },
			}
		},
		"3": { 
			name: "LASS",
			class: "Lass",
			//image: "https://archives.bulbagarden.net/media/upload/4/46/Spr_FRLG_Lass.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Lass.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Lass.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "JANICE" },
				"2": { name: "SALLY" },
				"3": { name: "ROBIN" },
				"4": { name: "CRISSY" },
				"5": { name: "MIRIAM" },
				"6": { name: "IRIS" },
				"7": { name: "RELI" },
				"8": { name: "ALI" },
				"9": { name: "THE NIDORAN GIRL, KELSEY" },
				"10": { name: "HALEY" },
				"11": { name: "ANN" },
				"12": { name: "" },
				"13": { name: "PAIGE" },
				"14": { name: "ANDREA" },
				"15": { name: "MEGAN" },
				"16": { name: "JULIA" },
				"17": { name: "KAY" },
				"18": { name: "LISA" },
				"19": { name: "" },
			}
		},
		"4": { 
			name: "SAILOR",
			class: "Sailor",
			//image: "https://archives.bulbagarden.net/media/upload/8/82/Spr_RS_Sailor_JP.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_RS_Sailor_JP.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_RS_Sailor_JP.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "EDMOND" },
				"2": { name: "TREVOR" },
				"3": { name: "LEONARD" },
				"4": { name: "DUNCAN" },
				"5": { name: "HUEY" },
				"6": { name: "DYLAN" },
				"7": { name: "PHILLIP" },
				"8": { name: "DWAYNE" },
			}
		},
		"5": { 
			name: "JR.TRAINER\u2642",
			class: "JrTrainerM",
			//image: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Camper.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/File:Spr_FRLG_Camper.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Camper.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "LIAM" },
				"2": { name: "SHANE" },
				"3": { name: "ETHAN" },
				"4": { name: "RICKY" },
				"5": { name: "JEFF" },
				"6": { name: "" },
				"7": { name: "CHRIS" },
				"8": { name: "DREW" },
				"9": { name: "JUSTIN" },
				"10": { name: "JOE" },
			}
		},
		"6": { 
			name: "JR.TRAINER\u2640",
			class: "JrTrainerF",
			//image: "https://archives.bulbagarden.net/media/upload/a/a0/Spr_FRLG_Picnicker.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Picnicker.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Picnicker.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "DIANA" },
				"2": { name: "NANCY" },
				"3": { name: "THE PIDGEY GIRL \"SANDY\" ISABELLE" },
				"4": { name: "" },
				"5": { name: "ALICIA" },
				"6": { name: "CAITLIN" },
				"7": { name: "HEIDI" },
				"8": { name: "CAROL" },
				"9": { name: "SOFIA" },
				"10": { name: "MARTHA" },
				"11": { name: "TINA" },
				"12": { name: "SUSIE" },
				"13": { name: "VALERIE" },
				"14": { name: "GWEN" },
				"15": { name: "ALMA" },
				"16": { name: "MISSY" },
				"17": { name: "LEAH" },
				"18": { name: "DANA" },
				"19": { name: "ARIANA" },
				"20": { name: "KINDRA" },
				"21": { name: "BECKY" },
				"22": { name: "CELIA" },
				"23": { name: "YAZMIN" },
				"24": { name: "IRENE" },
				"25": { name: "GISELLE" },
			}
		},
		"7": { 
			name: "POK\xE9MANIAC",
			class: "Pokemaniac",
			//image: "https://archives.bulbagarden.net/media/upload/0/0e/Spr_FRLG_Pok%C3%A9Maniac.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Pok%C3%A9Maniac.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Pok%C3%A9Maniac.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "MARK" },
				"2": { name: "HERMAN" },
				"3": { name: "COOPER" },
				"4": { name: "STEVE" },
				"5": { name: "WINSTON" },
				"6": { name: "DAWSON" },
				"7": { name: "ASHTON" },
			}
		},
		"8": { 
			name: "SUPER NERD",
			class: "SuperNerd",
			//image: "https://archives.bulbagarden.net/media/upload/1/1f/Spr_FRLG_Super_Nerd.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Super_Nerd.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Super_Nerd.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "JOVAN" },
				"2": { name: "MIGUEL" },
				"3": { name: "AIDAN" },
				"4": { name: "GLENN" },
				"5": { name: "LESLIE" },
				"6": { name: "" },
				"7": { name: "" },
				"8": { name: "" },
				"9": { name: "ERIK" },
				"10": { name: "AVERY" },
				"11": { name: "DEREK" },
				"12": { name: "ZAC" },
			}
		},
		"9": { 
			name: "HIKER",
			class: "Hiker",
			//image: "https://archives.bulbagarden.net/media/upload/8/8c/Spr_FRLG_Hiker.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Hiker.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Hiker.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "MARCOS" },
				"2": { name: "FRANKLIN" },
				"3": { name: "NOB" },
				"4": { name: "WAYNE" },
				"5": { name: "ALAN" },
				"6": { name: "BRICE" },
				"7": { name: "CLARK" },
				"8": { name: "TRENT" },
				"9": { name: "DUDLEY" },
				"10": { name: "ALLEN" },
				"11": { name: "JEREMY" },
				"12": { name: "LENNY" },
				"13": { name: "OLIVER" },
				"14": { name: "LUCAS" },
			}
		},
		"10": { 
			name: "BIKER",
			class: "Biker",
			//image: "https://archives.bulbagarden.net/media/upload/6/6e/Spr_FRLG_Biker.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Biker.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Biker.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "JARED" },
				"2": { name: "MALIK" },
				"3": { name: "ERNEST" },
				"4": { name: "ALEX" },
				"5": { name: "LAO" },
				"6": { name: "HIDEO" },
				"7": { name: "" },
				"8": { name: "VIRGIL" },
				"9": { name: "BILLY" },
				"10": { name: "NIKOLAS" },
				"11": { name: "JAXON" },
				"12": { name: "WILLIAM" },
				"13": { name: "LUKAS" },
				"14": { name: "ISAAC" },
				"15": { name: "GERALD" },
			}
		},
		"11": { 
			name: "BURGLAR",
			class: "Burglar",
			//image: "https://archives.bulbagarden.net/media/upload/7/78/Spr_FRLG_Burglar.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Burglar.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Burglar.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "" },
				"2": { name: "" },
				"3": { name: "" },
				"4": { name: "QUINN" },
				"5": { name: "RAMON" },
				"6": { name: "DUSTY" },
				"7": { name: "ARNIE" },
				"8": { name: "SIMON" },
				"9": { name: "LEWIS" },
			}
		},
		"12": { 
			name: "ENGINEER",
			class: "Engineer",
			//image: "https://archives.bulbagarden.net/media/upload/7/71/Spr_FRLG_Engineer.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Engineer.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Engineer.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "BAILY" },
				"2": { name: "BRAXTON" },
				"3": { name: "BERNIE" },
			}
		},
		"13": { 
			name: "JUGGLER",
			class: "UnusedJuggler",
			//image: "https://archives.bulbagarden.net/media/upload/5/50/Spr_FRLG_Juggler.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Juggler.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Juggler.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
			}
		},
		"14": { 
			name: "FISHERMAN",
			class: "Fisher",
			//image: "https://archives.bulbagarden.net/media/upload/c/c7/Spr_FRLG_Fisherman.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Fisherman.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Fisherman.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "DALE" },
				"2": { name: "BARNY" },
				"3": { name: "NED" },
				"4": { name: "CHIP" },
				"5": { name: "HANK" },
				"6": { name: "ELLIOT" },
				"7": { name: "RONALD" },
				"8": { name: "CLAUDE" },
				"9": { name: "WADE" },
				"10": { name: "NOLAN" },
				"11": { name: "ANDREW" },
			}
		},
		"15": { 
			name: "SWIMMER",
			class: "Swimmer",
			//image: "https://archives.bulbagarden.net/media/upload/9/95/Spr_FRLG_Swimmer_M.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Swimmer_M.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Swimmer_M.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "LUIS" },
				"2": { name: "RICHARD" },
				"3": { name: "REECE" },
				"4": { name: "MATTHEW" },
				"5": { name: "DOUGLAS" },
				"6": { name: "DAVID" },
				"7": { name: "TONY" },
				"8": { name: "AXLE" },
				"9": { name: "BARRY" },
				"10": { name: "DEAN" },
				"11": { name: "DARRIN" },
				"12": { name: "SPENCER" },
				"13": { name: "JACK" },
				"14": { name: "JEROME" },
				"15": { name: "ROLAND" },
			}
		},
		"16": { 
			name: "CUE BALL",
			class: "CueBall",
			//image: "https://archives.bulbagarden.net/media/upload/1/19/Spr_FRLG_Cue_Ball.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Cue_Ball.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Cue_Ball.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "KOJI" },
				"2": { name: "LUKE" },
				"3": { name: "CAMRON" },
				"4": { name: "RAUL" },
				"5": { name: "ISAIAH" },
				"6": { name: "ZEEK" },
				"7": { name: "JAMAL" },
				"8": { name: "COREY" },
				"9": { name: "CHASE" },
			}
		},
		"17": { 
			name: "GAMBLER",
			class: "Gambler",
			//image: "https://archives.bulbagarden.net/media/upload/1/1e/Spr_FRLG_Gamer.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Gamer.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Gamer.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "HUGO" },
				"2": { name: "JASPER" },
				"3": { name: "DIRK" },
				"4": { name: "DARIAN" },
				"5": { name: "STAN" },
				"6": { name: "" },
				"7": { name: "RICH" },
			}
		},
		"18": { 
			name: "BEAUTY",
			class: "Beauty",
			//image: "https://archives.bulbagarden.net/media/upload/3/39/Spr_FRLG_Beauty.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Beauty.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Beauty.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "BRIDGET" },
				"2": { name: "TAMIA" },
				"3": { name: "LORI" },
				"4": { name: "LOLA" },
				"5": { name: "SHEILA" },
				"6": { name: "TIFFANY" },
				"7": { name: "NORA" },
				"8": { name: "MELISSA" },
				"9": { name: "GRACE" },
				"10": { name: "OLIVIA" },
				"11": { name: "LAUREN" },
				"12": { name: "ANYA" },
				"13": { name: "ALICE" },
				"14": { name: "CONNIE" },
				"15": { name: "SHIRLEY" },
			}
		},
		"19": { name: "PSYCHIC",
			class: "Psychic",
			//image: "https://archives.bulbagarden.net/media/upload/e/ea/Spr_FRLG_Psychic_M.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Psychic_M.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Psychic_M.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "JOHAN" },
				"2": { name: "TYRON" },
				"3": { name: "CAMERON" },
				"4": { name: "PRESTON" },
			}
		},
		"20": { name: "ROCKER",
			class: "Rocker",
			//image: "https://archives.bulbagarden.net/media/upload/f/f3/Spr_FRLG_Rocker.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Rocker.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Rocker.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "RANDALL" },
				"2": { name: "LUCA" },
			}
		},
		"21": { name: "JUGGLER",
			class: "Juggler",
			//image: "https://archives.bulbagarden.net/media/upload/5/50/Spr_FRLG_Juggler.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Juggler.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Juggler.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "DALTON" },
				"2": { name: "NELSON" },
				"3": { name: "KIRK" },
				"4": { name: "SHAWN" },
				"5": { name: "GREGORY" },
				"6": { name: "" },
				"7": { name: "KAYDEN" },
				"8": { name: "NATE" },
			}
		},
		"22": { name: "TAMER",
			class: "Tamer",
			//image: "https://archives.bulbagarden.net/media/upload/8/89/Spr_FRLG_Tamer.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Tamer.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Tamer.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "PHIL" },
				"2": { name: "EDGAR" },
				"3": { name: "JASON" },
				"4": { name: "COLE" },
				"5": { name: "VINCENT" },
				"6": { name: "JOHN" },
			}
		},
		"23": { name: "BIRD KEEPER",
			class: "BirdKeeper",
			//image: "https://archives.bulbagarden.net/media/upload/b/b2/Spr_FRLG_Bird_Keeper.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Bird_Keeper.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Bird_Keeper.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "SEBASTIAN" },
				"2": { name: "PERRY" },
				"3": { name: "ROBERT" },
				"4": { name: "DONALD" },
				"5": { name: "BENNY" },
				"6": { name: "EDWIN" },
				"7": { name: "CHESTER" },
				"8": { name: "WILTON" },
				"9": { name: "RAMIRO" },
				"10": { name: "JACOB" },
				"11": { name: "ROGER" },
				"12": { name: "REED" },
				"13": { name: "KEITH" },
				"14": { name: "CARTER" },
				"15": { name: "MITCH" },
				"16": { name: "BECK" },
				"17": { name: "MARLON" },
			}
		},
		"24": { name: "BLACKBELT",
			class: "Blackbelt",
			//image: "https://archives.bulbagarden.net/media/upload/8/8e/Spr_FRLG_Black_Belt.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Black_Belt.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Black_Belt.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "KOICHI" },
				"2": { name: "MIKE" },
				"3": { name: "HIDEKI" },
				"4": { name: "AARON" },
				"5": { name: "HITOSHI" },
				"6": { name: "ATSUSHI" },
				"7": { name: "KIYO" },
				"8": { name: "TAKASHI" },
				"9": { name: "DAISUKE" },
			}
		},
		"25": { name: "***RivalName***",
			class: "Rival1",
			//image: "https://archives.bulbagarden.net/media/upload/0/02/Spr_FRLG_Blue_1.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Blue_1.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Blue_1.png",
			teams: {
				"": { },
				"0": { },
				"1": { },
				"2": { },
				"3": { },
			}
		},
		"26": { name: "PROF.OAK",
			class: "ProfOak",
			//image: "https://archives.bulbagarden.net/media/upload/4/4c/Spr_FRLG_Oak.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Oak.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Oak.png",
			teams: {
				"": { },
				"0": { },
				"1": { },
				"2": { },
				"3": { },
			}
		},
		"27": { name: "CHIEF",
			class: "Chief",
			//image: "https://archives.bulbagarden.net/media/upload/f/f9/Spr_FRLG_Scientist.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Scientist.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Scientist.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
			}
		},
		"28": { name: "SCIENTIST",
			class: "Scientist",
			//image: "https://archives.bulbagarden.net/media/upload/f/f9/Spr_FRLG_Scientist.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Scientist.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Scientist.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "" },
				"2": { name: "CONNOR" },
				"3": { name: "JERRY" },
				"4": { name: "JOSE" },
				"5": { name: "RODNEY" },
				"6": { name: "BEAU" },
				"7": { name: "TAYLOR" },
				"8": { name: "JOSHUA" },
				"9": { name: "PARKER" },
				"10": { name: "ED" },
				"11": { name: "TRAVIS" },
				"12": { name: "BRAYDON" },
				"13": { name: "IVAN" },
			}
		},
		"29": { name: "GIOVANNI",
			class: "Giovanni",
			//image: "https://archives.bulbagarden.net/media/upload/4/41/Spr_FRLG_Giovanni.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Giovanni.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Giovanni.png",
			teams: {
				"": { },
				"0": { },
				"1": { },
				"2": { },
				"3": { prefix: "LEADER" },
			}
		},
		"30": { name: "ROCKET",
			class: "Rocket",
			//image: "https://archives.bulbagarden.net/media/upload/8/85/Spr_FRLG_Team_Rocket_Grunt_M.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Team_Rocket_Grunt_M.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Team_Rocket_Grunt_M.png",
			teams: {
				"": { name: "GRUNT" },
				"0": { name: "GRUNT" },
				"1": { name: "GRUNT" },
				"2": { name: "GRUNT" },
				"3": { name: "GRUNT" },
				"4": { name: "GRUNT" },
				"5": { name: "GRUNT" },
				"6": { name: "GRUNT" },
				"7": { name: "GRUNT" },
				"8": { name: "GRUNT" },
				"9": { name: "GRUNT" },
				"10": { name: "GRUNT" },
				"11": { name: "GRUNT" },
				"12": { name: "GRUNT" },
				"13": { name: "GRUNT" },
				"14": { name: "GRUNT" },
				"15": { name: "GRUNT" },
				"16": { name: "GRUNT" },
				"17": { name: "GRUNT" },
				"18": { name: "GRUNT" },
				"19": { name: "GRUNT" },
				"20": { name: "GRUNT" },
				"21": { name: "GRUNT" },
				"22": { name: "GRUNT" },
				"23": { name: "GRUNT" },
				"24": { name: "GRUNT" },
				"25": { name: "GRUNT" },
				"26": { name: "GRUNT" },
				"27": { name: "GRUNT" },
				"28": { name: "GRUNT" },
				"29": { name: "GRUNT" },
				"30": { name: "GRUNT" },
				"31": { name: "GRUNT" },
				"32": { name: "GRUNT" },
				"33": { name: "GRUNT" },
				"34": { name: "GRUNT" },
				"35": { name: "GRUNT" },
				"36": { name: "GRUNT" },
				"37": { name: "GRUNT" },
				"38": { name: "GRUNT" },
				"39": { name: "GRUNT" },
				"40": { name: "GRUNT" },
				"41": { name: "GRUNT" },
				"42": { fullname: "TEAM ROCKET", image: "https://static.merkelhaus.us/overlayimages/trainers/team_rocket_jessie_james__ingame_battle_sprite__by_ogjazz_defuy5c-fullview.png" },
				"43": { fullname: "TEAM ROCKET", image: "https://static.merkelhaus.us/overlayimages/trainers/team_rocket_jessie_james__ingame_battle_sprite__by_ogjazz_defuy5c-fullview.png" },
				"44": { fullname: "TEAM ROCKET", image: "https://static.merkelhaus.us/overlayimages/trainers/team_rocket_jessie_james__ingame_battle_sprite__by_ogjazz_defuy5c-fullview.png" },
				"45": { fullname: "TEAM ROCKET", image: "https://static.merkelhaus.us/overlayimages/trainers/team_rocket_jessie_james__ingame_battle_sprite__by_ogjazz_defuy5c-fullview.png" },
				"46": { name: "GRUNT" },
				"47": { name: "GRUNT" },
				"48": { name: "GRUNT" },
				"49": { name: "GRUNT" },
				// https://static.merkelhaus.us/overlayimages/trainers/team_rocket_butch_cassidy__ingame_battle_sprite__by_ogjazz_defwg8e-fullview.png
			}
		},
		"31": { name: "COOLTRAINER\u2642",
			class: "CooltrainerM",
			//image: "https://archives.bulbagarden.net/media/upload/b/b8/Spr_FRLG_Cooltrainer_M.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Cooltrainer_M.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Cooltrainer_M.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "SAMUEL" },
				"2": { name: "GEORGE" },
				"3": { name: "COLBY" },
				"4": { name: "PAUL" },
				"5": { name: "ROLANDO" },
				"6": { name: "GILBERT" },
				"7": { name: "OWEN" },
				"8": { name: "BERKE" },
				"9": { name: "YUJI" },
				"10": { name: "WARREN" },
			}
		},
		"32": { name: "COOLTRAINER\u2640",
			class: "CooltrainerF",
			//image: "https://archives.bulbagarden.net/media/upload/7/7f/Spr_FRLG_Cooltrainer_F.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Cooltrainer_F.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Cooltrainer_F.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "MARY" },
				"2": { name: "CAROLINE" },
				"3": { name: "ALEXA" },
				"4": { name: "SHANNON" },
				"5": { name: "NAOMI" },
				"6": { name: "BROOKE" },
				"7": { name: "AUSTINA" },
				"8": { name: "JULIE" },
			}
		},
		"33": { name: "ELITE FOUR",
			class: "Bruno",
			//image: "https://archives.bulbagarden.net/media/upload/f/f7/Spr_FRLG_Bruno.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Bruno.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Bruno.png",
			teams: {
				"": { name: "BRUNO" },
				"0": { name: "BRUNO" },
				"1": { name: "BRUNO" },
			}
		},
		"34": { name: "LEADER",
			class: "Brock",
			//image: "https://archives.bulbagarden.net/media/upload/7/7c/Spr_FRLG_Brock.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Brock.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Brock.png",
			teams: {
				"": { name: "BROCK" },
				"0": { name: "BROCK" },
				"1": { name: "BROCK" },
			}
		},
		"35": { name: "LEADER",
			class: "Misty",
			//image: "https://archives.bulbagarden.net/media/upload/2/2c/Spr_FRLG_Misty.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Misty.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Misty.png",
			teams: {
				"": { name: "MISTY" },
				"0": { name: "MISTY" },
				"1": { name: "MISTY" },
			}
		},
		"36": { name: "LEADER",
			class: "LtSurge",
			//image: "https://archives.bulbagarden.net/media/upload/5/5c/Spr_FRLG_Lt_Surge.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Lt_Surge.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Lt_Surge.png",
			teams: {
				"": { name: "LT.SURGE" },
				"0": { name: "LT.SURGE" },
				"1": { name: "LT.SURGE" },
			}
		},
		"37": { name: "LEADER",
			class: "Erika",
			//image: "https://archives.bulbagarden.net/media/upload/c/c9/Spr_FRLG_Erika.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Erika.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Erika.png",
			teams: {
				"": { name: "ERIKA" },
				"0": { name: "ERIKA" },
				"1": { name: "ERIKA" },
			}
		},
		"38": { name: "LEADER",
			class: "Koga",
			//image: "https://archives.bulbagarden.net/media/upload/0/02/Spr_FRLG_Koga.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Koga.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Koga.png",
			teams: {
				"": { name: "KOGA" },
				"0": { name: "KOGA" },
				"1": { name: "KOGA" },
			}
		},
		"39": { name: "LEADER",
			class: "Blaine",
			//image: "https://archives.bulbagarden.net/media/upload/6/6d/Spr_FRLG_Blaine.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Blaine.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Blaine.png",
			teams: {
				"": { name: "BLAINE" },
				"0": { name: "BLAINE" },
				"1": { name: "BLAINE" },
			}
		},
		"40": { name: "LEADER",
			class: "Sabrina",
			//image: "https://archives.bulbagarden.net/media/upload/d/dd/Spr_FRLG_Sabrina.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Sabrina.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Sabrina.png",
			teams: {
				"": { name: "SABRINA" },
				"0": { name: "SABRINA" },
				"1": { name: "SABRINA" },
			}
		},
		"41": { name: "GENTLEMAN",
			class: "Gentleman",
			//image: "https://archives.bulbagarden.net/media/upload/9/94/Spr_FRLG_Gentleman.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Gentleman.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Gentleman.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "THOMAS" },
				"2": { name: "ARTHUR" },
				"3": { name: "TUCKER" },
				"4": { name: "UNNAMED" },
				"5": { name: "LAMAR" },
			}
		},
		"42": { name: "***RivalName***",
			class: "Rival2",
			//image: "https://archives.bulbagarden.net/media/upload/e/e2/Spr_FRLG_Blue_2.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Blue_2.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Blue_2.png",
			teams: {
				"": { },
				"0": { },
				"1": { },
				"2": { },
				"3": { },
				"4": { },
				"5": { },
				"6": { },
				"7": { },
				"8": { },
				"9": { },
				"10": { },
			}
		},
		"43": { name: "CHAMPION",
			class: "Rival3",
			//image: "https://archives.bulbagarden.net/media/upload/1/10/Spr_FRLG_Blue_3.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Blue_3.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Blue_3.png",
			teams: {
				"": { name: "***RivalName***" },
				"0": { name: "***RivalName***" },
				"1": { name: "***RivalName***" },
				"2": { name: "***RivalName***" },
				"3": { name: "***RivalName***" },
			}
		},
		"44": { name: "ELITE FOUR",
			class: "Lorelei",
			//image: "https://archives.bulbagarden.net/media/upload/d/db/Spr_FRLG_Lorelei.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Lorelei.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Lorelei.png",
			teams: {
				"": { name: "LORELEI" },
				"0": { name: "LORELEI" },
				"1": { name: "LORELEI" },
			}
		},
		"45": { name: "CHANNELER",
			class: "Channeler",
			//image: "https://archives.bulbagarden.net/media/upload/1/1e/Spr_FRLG_Channeler.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Channeler.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Channeler.png",
			teams: {
				"": { name: "" },
				"0": { name: "" },
				"1": { name: "UNNAMED" },
				"2": { name: "UNNAMED" },
				"3": { name: "UNNAMED" },
				"4": { name: "UNNAMED" },
				"5": { name: "CARLY" },
				"6": { name: "HOPE" },
				"7": { name: "UNNAMED" },
				"8": { name: "PATRICIA" },
				"9": { name: "JODY" },
				"10": { name: "LAUREL" },
				"11": { name: "UNNAMED" },
				"12": { name: "PAULA" },
				"13": { name: "UNNAMED" },
				"14": { name: "JANAE" },
				"15": { name: "UNNAMED" },
				"16": { name: "KARINA" },
				"17": { name: "RUTH" },
				"18": { name: "TAMMY" },
				"19": { name: "ANGELICA" },
				"20": { name: "EMILIA" },
				"21": { name: "JENNIFER" },
				"22": { name: "AMANDA" },
				"23": { name: "STACY" },
				"24": { name: "TASHA" },
			}
		},
		"46": { name: "ELITE FOUR",
			class: "Agatha",
			//image: "https://archives.bulbagarden.net/media/upload/5/56/Spr_FRLG_Agatha.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Agatha.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Agatha.png",
			teams: {
				"": { name: "AGATHA" },
				"0": { name: "AGATHA" },
				"1": { name: "AGATHA" },
			}
		},
		"47": { name: "ELITE FOUR",
			class: "Lance",
			//image: "https://archives.bulbagarden.net/media/upload/f/fb/Spr_FRLG_Lance.png",
			image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_FRLG_Lance.png",
			reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Lance.png",
			teams: {
				"": { name: "LANCE" },
				"0": { name: "LANCE" },
				"1": { name: "LANCE" },
			}
		},
	};
  
	private static trainersLookupTeamsMap = this.objMap(this.trainersLookupKV, (k, v) => { k === "teams" ? new Map(Object.entries(v)) : v; }, (k, v) => { return k !== "teams"; });
	public static trainersLookup = new Map(Object.entries(this.trainersLookupTeamsMap));

	return ( <></> );
};

export default TrainersLookup;
