import * as typeStyles from '../../Types.module';
import ITypeLookup from '../Interfaces/ITypeLookup'
import { NumberOrString } from 'Util'
import IType from '../Interfaces/IType'

export class TypeLookup implements ITypeLookup {
    private typeLookupKV: { [key: string | number]: IType } = {
        0x00: { name: "Normal", old_css_class: typeStyles.normal_type_old, new_css_class: typeStyles.normal_type_new },
        0x01: { name: "Fighting", old_css_class: typeStyles.fighting_type_old, new_css_class: typeStyles.fighting_type_new },
        0x02: { name: "Flying", old_css_class: typeStyles.flying_type_old, new_css_class: typeStyles.flying_type_new },
        0x03: { name: "Poison", old_css_class: typeStyles.poison_type_old, new_css_class: typeStyles.poison_type_new },
        0x04: { name: "Ground", old_css_class: typeStyles.ground_type_old, new_css_class: typeStyles.ground_type_new },
        0x05: { name: "Rock", old_css_class: typeStyles.rock_type_old, new_css_class: typeStyles.rock_type_new },
        0x06: { name: "BIRD", old_css_class: typeStyles.bird_type_old, new_css_class: typeStyles.bird_type_new },
        0x07: { name: "Bug", old_css_class: typeStyles.bug_type_old, new_css_class: typeStyles.bug_type_new },
        0x08: { name: "Ghost", old_css_class: typeStyles.ghost_type_old, new_css_class: typeStyles.ghost_type_new },
        0x09: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0A: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0B: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0C: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0D: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0E: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0F: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x10: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x11: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x12: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x13: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x14: { name: "Fire", old_css_class: typeStyles.fire_type_old, new_css_class: typeStyles.fire_type_new },
        0x15: { name: "Water", old_css_class: typeStyles.water_type_old, new_css_class: typeStyles.water_type_new },
        0x16: { name: "Grass", old_css_class: typeStyles.grass_type_old, new_css_class: typeStyles.grass_type_new },
        0x17: { name: "Electric", old_css_class: typeStyles.electric_type_old, new_css_class: typeStyles.electric_type_new },
        0x18: { name: "Psychic", old_css_class: typeStyles.psychic_type_old, new_css_class: typeStyles.psychic_type_new },
        0x19: { name: "Ice", old_css_class: typeStyles.ice_type_old, new_css_class: typeStyles.ice_type_new },
        0x1A: { name: "Dragon", old_css_class: typeStyles.dragon_type_old, new_css_class: typeStyles.dragon_type_new },
        0x1B: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1C: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1D: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1E: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1F: { name: "9 99 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x20: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x21: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x22: { name: "s.a. Enemy (PKMN)W n:LC(RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x23: { name: "9 99 9\\9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x24: { name: "9II9toto9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x25: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x26: { name: "9 9 9 99 ||9 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x27: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x28: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x29: { name: "Enemy (PKMN)W n:LC(RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2A: { name: "99 9 ||99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2B: { name: "98 9\u300E 9 29|| 99\ 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2C: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2D: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2E: { name: "9'>99HP99 'v9 9 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2F: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x30: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x31: { name: "9 99A 9Aa9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x32: { name: "(Many 9s)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x33: { name: "(Many 9s)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x34: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x35: { name: "9 99 9II9toto9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x36: { name: ". .s.a Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x37: { name: "9 A9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x38: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x39: { name: "99 9 || ||9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3A: { name: ". .s.a Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3B: { name: "9 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3C: { name: ". .s.a Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3D: { name: "96 (plus many 9s)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3E: { name: "9 99\u20BD 9 9 99 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3F: { name: "9 \u20BD 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x40: { name: "99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x41: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x42: { name: "B Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x43: { name: "9 9 9 9 ||99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x44: { name: "99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x45: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x46: { name: "9 9 9 99 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x47: { name: "9 99 99Q", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x48: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x49: { name: "99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4A: { name: "99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4B: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4C: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4D: { name: "Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4E: { name: "3l\u30A5", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4F: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x50: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x51: { name: "TM .", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x52: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x53: { name: "V", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x54: { name: "HP UGCSf G:YELLOW E \u300C (PKMN) G;\xE9 V:Ue ( F", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x55: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x56: { name: "(name of selected move)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x57: { name: "\u30A5( p\u2640", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x58: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x59: { name: "\u20BD9? \u30A5", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5A: { name: "(illegible extremely long name)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5B: { name: "YOUNGSTER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5C: { name: "BUG CATCHER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5D: { name: "LASS", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5E: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5F: { name: "JR.TRAINER\u2642", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x60: { name: "JR.TRAINER\u2640", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x61: { name: "POK\xE9MANIAC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x62: { name: "SUPER NERD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x63: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x64: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x65: { name: "BURGLAR", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x66: { name: "ENGINEER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x67: { name: "JUGGLER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x68: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x69: { name: "SWIMMER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6A: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6B: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6C: { name: "BEAUTY", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6D: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6E: { name: "ROCKER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6F: { name: "JUGGLER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x70: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x71: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x72: { name: "BLACKBELT", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x73: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x74: { name: "PROF.OAK", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x75: { name: "CHIEF", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x76: { name: "SCIENTIST", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x77: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x78: { name: "ROCKET", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x79: { name: "COOLTRAINER\u2642", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7A: { name: "COOLTRAINER\u2640", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7B: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7C: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7D: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7E: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7F: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x80: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x81: { name: "FIGHTING", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x82: { name: "FLYING", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x83: { name: "POISON", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x84: { name: "GROUND", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x85: { name: "ROCK", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x86: { name: "BIRD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x87: { name: "BUG", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x88: { name: "GHOST", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x89: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8A: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8B: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8C: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8D: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8E: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8F: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x90: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x91: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x92: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x93: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x94: { name: "FIRE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x95: { name: "WATER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x96: { name: "GRASS", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x97: { name: "ELECTRIC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x98: { name: "PSYCHIC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x99: { name: "ICE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9A: { name: "DRAGON", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9B: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9C: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9D: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9E: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9F: { name: "9 99 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA0: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA1: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA2: { name: "s.a. Enemy (PKMN)W n:LC(RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA3: { name: "9 99 9\\9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA4: { name: "9II9toto9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA5: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA6: { name: "9 9 9 99 ||9 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA7: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA8: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA9: { name: "Enemy (PKMN)W n:LC(RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAA: { name: "99 9 ||99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAB: { name: "98 9\u300E 9 29|| 99\ 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAC: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAD: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAE: { name: "9'>99HP99 'v9 9 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAF: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB0: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB1: { name: "9 99A 9Aa9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB2: { name: "(Many 9s)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB3: { name: "(Many 9s)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB4: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB5: { name: "9 99 9II9toto9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB6: { name: ". .s.a Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB7: { name: "9 A9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB8: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB9: { name: "99 9 || ||9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBA: { name: ". .s.a Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBB: { name: "9 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBC: { name: ". .s.a Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBD: { name: "96 (plus many 9s)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBE: { name: "9 99\u20BD 9 9 99 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBF: { name: "9 \u20BD 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC0: { name: "99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC1: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC2: { name: "B Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC3: { name: "9 9 9 9 ||99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC4: { name: "99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC5: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC6: { name: "9 9 9 99 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC7: { name: "9 99 99Q", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC8: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC9: { name: "99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCA: { name: "99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCB: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCC: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCD: { name: "Enemy (PKMN)W n L:C O (RIVAL)C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCE: { name: "3l\u30A5", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCF: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD0: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD1: { name: "TM .", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD2: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD3: { name: "V", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD4: { name: "HP UGCSf G:YELLOW E \u300C (PKMN) G;\xE9 V:Ue ( F", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD5: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD6: { name: "(name of selected move)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD7: { name: "\u30A5( p\u2640", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD8: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD9: { name: "\u20BD9? \u30A5", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDA: { name: "(illegible extremely long name)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDB: { name: "YOUNGSTER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDC: { name: "BUG CATCHER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDD: { name: "LASS", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDE: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDF: { name: "JR.TRAINER\u2642", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE0: { name: "JR.TRAINER\u2640", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE1: { name: "POK\xE9MANIAC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE2: { name: "SUPER NERD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE3: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE4: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE5: { name: "BURGLAR", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE6: { name: "ENGINEER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE7: { name: "JUGGLER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE8: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE9: { name: "SWIMMER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEA: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEB: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEC: { name: "BEAUTY", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xED: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEE: { name: "ROCKER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEF: { name: "JUGGLER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF0: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF1: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF2: { name: "BLACKBELT", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF3: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF4: { name: "PROF.OAK", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF5: { name: "CHIEF", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF6: { name: "SCIENTIST", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF7: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF8: { name: "ROCKET", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF9: { name: "COOLTRAINER\u2642", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFA: { name: "COOLTRAINER\u2640", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFB: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFC: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFD: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFE: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFF: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
    };

    private keyValuePairs: [string | number, IType][] = Object.entries(this.typeLookupKV).map(([key, value]) => [NumberOrString(key), value]);
    public typeLookup: Map<string | number, IType> = new Map<string | number, IType>(this.keyValuePairs);
};

export default TypeLookup;
