import ITrainersLookup from '../Interfaces/ITrainersLookup'
import { NumberOrString, objMap } from 'Util'
import { ITrainerInternal, ITrainer, ITrainerTeam } from '../Interfaces/ITrainer';

export class TrainersLookup implements ITrainersLookup {
    private trainersLookupKV: { [key: string | number]: ITrainerInternal } = {
        "": {
            name: "",
            class: "",
            //image: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D",
            image: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D",
            reference: "https://stackoverflow.com/a/19126281",
            teams: {
                "": { name: "" },
                "0": { name: "" },
            }
        }, // undefined / default value. 
        "0": {
            name: "",
            class: "",
            //image: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D",
            image: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D",
            reference: "https://stackoverflow.com/a/19126281",
            teams: {
                "": { name: "" },
                "0": { name: "" },
            }
        }, // undefined / default value. 
        "1": {
            name: "LEADER",
            class: "Falkner",
            //image: "https://archives.bulbagarden.net/media/upload/2/2b/Spr_HGSS_Falkner.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Falkner.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Falkner.png",
            teams: {
                "": { name: "FALKNER" },
                "0": { name: "FALKNER" },
                "1": { name: "FALKNER" },
            }
        },
        "2": {
            name: "LEADER",
            class: "Whitney",
            //image: "https://archives.bulbagarden.net/media/upload/f/fc/Spr_HGSS_Whitney.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Whitney.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Whitney.png",
            teams: {
                "": { name: "WHITNEY" },
                "0": { name: "WHITNEY" },
                "1": { name: "WHITNEY" },
            }
        },
        "3": {
            name: "LEADER",
            class: "Bugsy",
            //image: "https://archives.bulbagarden.net/media/upload/b/b6/Spr_HGSS_Bugsy.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Bugsy.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Bugsy.png",
            teams: {
                "": { name: "BUGSY" },
                "0": { name: "BUGSY" },
                "1": { name: "BUGSY" },
            }
        },
        "4": {
            name: "LEADER",
            class: "Morty",
            //image: "https://archives.bulbagarden.net/media/upload/archive/c/ca/20240316190058%21Spr_HGSS_Morty.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Morty.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Morty.png",
            teams: {
                "": { name: "MORTY" },
                "0": { name: "MORTY" },
                "1": { name: "MORTY" },
            }
        },
        "5": {
            name: "LEADER",
            class: "Pryce",
            //image: "https://archives.bulbagarden.net/media/upload/4/43/Spr_HGSS_Pryce.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Pryce.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Pryce.png",
            teams: {
                "": { name: "PRYCE" },
                "0": { name: "PRYCE" },
                "1": { name: "PRYCE" },
            }
        },
        "6": {
            name: "LEADER",
            class: "Jasmine",
            //image: "https://archives.bulbagarden.net/media/upload/archive/4/44/20240316190008%21Spr_HGSS_Jasmine.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Jasmine.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Jasmine.png",
            teams: {
                "": { name: "JASMINE" },
                "0": { name: "JASMINE" },
                "1": { name: "JASMINE" },
            }
        },
        "7": {
            name: "LEADER",
            class: "Chuck",
            //image: "https://archives.bulbagarden.net/media/upload/f/fd/Spr_HGSS_Chuck.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Chuck.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Chuck.png",
            teams: {
                "": { name: "CHUCK" },
                "0": { name: "CHUCK" },
                "1": { name: "CHUCK" },
            }
        },
        "8": {
            name: "LEADER",
            class: "Clair",
            //image: "https://archives.bulbagarden.net/media/upload/d/d7/Spr_HGSS_Clair.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Clair.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Clair.png",
            teams: {
                "": { name: "CLAIR" },
                "0": { name: "CLAIR" },
                "1": { name: "CLAIR" },
            }
        },
        "9": {
            name: "RIVAL",
            class: "Rival1",
            //image: "https://archives.bulbagarden.net/media/upload/9/95/Spr_HGSS_Silver.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Silver.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Silver.png",
            teams: {
                "": { name: "***RivalName***" },
                "0": { name: "***RivalName***" },
                "1": { name: "***RivalName***" },
                "2": { name: "***RivalName***" },
                "3": { name: "***RivalName***" },
                "4": { name: "***RivalName***" },
                "5": { name: "***RivalName***" },
                "6": { name: "***RivalName***" },
                "7": { name: "***RivalName***" },
                "8": { name: "***RivalName***" },
                "9": { name: "***RivalName***" },
                "10": { name: "***RivalName***" },
                "11": { name: "***RivalName***" },
                "12": { name: "***RivalName***" },
                "13": { name: "***RivalName***" },
                "14": { name: "***RivalName***" },
                "15": { name: "***RivalName***" },
            }
        },
        "10": {
            name: "POK\xE9MON PROF.",
            class: "PokemonProf",
            //image: "https://archives.bulbagarden.net/media/upload/f/fe/Spr_HGSS_Oak.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Oak.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Oak.png",
            teams: {
                "": { name: "OAK" },
                "0": { name: "OAK" },
            }
        },
        "11": {
            name: "ELITE FOUR",
            class: "Will",
            //image: "https://archives.bulbagarden.net/media/upload/f/fd/Spr_HGSS_Will.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Will.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Will.png",
            teams: {
                "": { name: "WILL" },
                "0": { name: "WILL" },
                "1": { name: "WILL" },
            }
        },
        "12": {
            name: "PKMN TRAINER",
            class: "Cal",
            //image: "https://archives.bulbagarden.net/media/upload/3/3b/Spr_HGSS_Ace_Trainer_M.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Ace_Trainer_M.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Ace_Trainer_M.png",
            teams: {
                "": { name: "CAL" },
                "0": { name: "CAL" },
                "1": { name: "CAL" },
                "2": { name: "CAL" },
                "3": { name: "CAL" },
            }
        },
        "13": {
            name: "ELITE FOUR",
            class: "Bruno",
            //image: "https://archives.bulbagarden.net/media/upload/e/ee/Spr_HGSS_Bruno.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Bruno.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Bruno.png",
            teams: {
                "": { name: "BRUNO" },
                "0": { name: "BRUNO" },
                "1": { name: "BRUNO" },
            }
        },
        "14": {
            name: "ELITE FOUR",
            class: "Karen",
            //image: "https://archives.bulbagarden.net/media/upload/a/a2/Spr_HGSS_Karen.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Karen.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Karen.png",
            teams: {
                "": { name: "KAREN" },
                "0": { name: "KAREN" },
                "1": { name: "KAREN" },
            }
        },
        "15": {
            name: "ELITE FOUR",
            class: "Koga",
            //image: "https://archives.bulbagarden.net/media/upload/1/18/Spr_HGSS_Koga.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Koga.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Koga.png",
            teams: {
                "": { name: "KOGA" },
                "0": { name: "KOGA" },
                "1": { name: "KOGA" },
            }
        },
        "16": {
            name: "CHAMPION",
            class: "Champion",
            //image: "https://archives.bulbagarden.net/media/upload/1/1f/Spr_HGSS_Lance.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Lance.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Lance.png",
            teams: {
                "": { name: "LANCE" },
                "0": { name: "LANCE" },
                "1": { name: "LANCE" },
            }
        },
        "17": {
            name: "LEADER",
            class: "Brock",
            //image: "https://archives.bulbagarden.net/media/upload/3/30/Spr_HGSS_Brock.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Brock.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Brock.png",
            teams: {
                "": { name: "BROCK" },
                "0": { name: "BROCK" },
                "1": { name: "BROCK" },
            }
        },
        "18": {
            name: "LEADER",
            class: "Misty",
            //image: "https://archives.bulbagarden.net/media/upload/d/d1/Spr_HGSS_Misty.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Misty.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Misty.png",
            teams: {
                "": { name: "MISTY" },
                "0": { name: "MISTY" },
                "1": { name: "MISTY" },
            }
        },
        "19": {
            name: "LEADER",
            class: "LtSurge",
            //image: "https://archives.bulbagarden.net/media/upload/1/1d/Spr_HGSS_Lt_Surge.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Lt_Surge.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Lt_Surge.png",
            teams: {
                "": { name: "LT.SURGE" },
                "0": { name: "LT.SURGE" },
                "1": { name: "LT.SURGE" },
            }
        },
        "20": {
            name: "SCIENTIST",
            class: "Scientist",
            //image: "https://archives.bulbagarden.net/media/upload/2/2b/Spr_HGSS_Scientist.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Scientist.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Scientist.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "ROSS" },
                "2": { name: "MITCH" },
                "3": { name: "JED" },
                "4": { name: "MARC" },
                "5": { name: "RICH" },
            }
        },
        "21": {
            name: "LEADER",
            class: "Erika",
            //image: "https://archives.bulbagarden.net/media/upload/c/c7/Spr_HGSS_Erika.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Erika.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Erika.png",
            teams: {
                "": { name: "ERIKA" },
                "0": { name: "ERIKA" },
                "1": { name: "ERIKA" },
            }
        },
        "22": {
            name: "YOUNGSTER",
            class: "Youngster",
            //image: "https://archives.bulbagarden.net/media/upload/d/d0/Spr_HGSS_Youngster.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Youngster.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Youngster.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "JOEY" },
                "2": { name: "MIKEY" },
                "3": { name: "ALBERT" },
                "4": { name: "GORDON" },
                "5": { name: "SAMUEL" },
                "6": { name: "IAN" },
                "7": { name: "JOEY" },
                "8": { name: "JOEY" },
                "9": { name: "WARREN" },
                "10": { name: "JIMMY" },
                "11": { name: "OWEN" },
                "12": { name: "JASON" },
                "13": { name: "JOEY" },
                "14": { name: "JOEY" },
            }
        },
        "23": {
            name: "SCHOOLBOY",
            class: "Schoolboy",
            //image: "https://archives.bulbagarden.net/media/upload/f/f4/Spr_HGSS_School_Kid.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_School_Kid.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_School_Kid.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "JACK" },
                "2": { name: "KIPP" },
                "3": { name: "ALAN" },
                "4": { name: "JOHNNY" },
                "5": { name: "DANNY" },
                "6": { name: "TOMMY" },
                "7": { name: "DUDLEY" },
                "8": { name: "JOE" },
                "9": { name: "BILLY" },
                "10": { name: "CHAD" },
                "11": { name: "NATE" },
                "12": { name: "RICKY" },
                "13": { name: "JACK" },
                "14": { name: "JACK" },
                "15": { name: "ALAN" },
                "16": { name: "ALAN" },
                "17": { name: "CHAD" },
                "18": { name: "CHAD" },
                "19": { name: "JACK" },
                "20": { name: "JACK" },
                "21": { name: "ALAN" },
                "22": { name: "ALAN" },
                "23": { name: "CHAD" },
                "24": { name: "CHAD" },
            }
        },
        "24": {
            name: "BIRD KEEPER",
            class: "BirdKeeper",
            //image: "https://archives.bulbagarden.net/media/upload/f/f2/Spr_HGSS_Bird_Keeper.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Bird_Keeper.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Bird_Keeper.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "ROD" },
                "2": { name: "ABE" },
                "3": { name: "BRYAN" },
                "4": { name: "THEO" },
                "5": { name: "TOBY" },
                "6": { name: "DENIS" },
                "7": { name: "VANCE" },
                "8": { name: "HANK" },
                "9": { name: "ROY" },
                "10": { name: "BORIS" },
                "11": { name: "BOB" },
                "12": { name: "JOSE" },
                "13": { name: "PETER" },
                "14": { name: "JOSE" },
                "15": { name: "PERRY" },
                "16": { name: "BRET" },
                "17": { name: "JOSE" },
                "18": { name: "VANCE" },
                "19": { name: "VANCE" },
            }
        },
        "25": {
            name: "LASS",
            class: "Lass",
            //image: "https://archives.bulbagarden.net/media/upload/2/2c/Spr_HGSS_Lass.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Lass.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Lass.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "CARRIE" },
                "2": { name: "BRIDGET" },
                "3": { name: "ALICE" },
                "4": { name: "KRISE" },
                "5": { name: "CONNIE" },
                "6": { name: "LINDA" },
                "7": { name: "LAURA" },
                "8": { name: "SHANNON" },
                "9": { name: "MICHELLE" },
                "10": { name: "DANA" },
                "11": { name: "ELLEN" },
                "12": { name: "CONNIE" },
                "13": { name: "CONNIE" },
                "14": { name: "DANA" },
                "15": { name: "DANA" },
                "16": { name: "DANA" },
                "17": { name: "DANA" },
            }
        },
        "26": {
            name: "LEADER",
            class: "Janine",
            //image: "https://archives.bulbagarden.net/media/upload/2/21/Spr_HGSS_Janine.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Janine.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Janine.png",
            teams: {
                "": { name: "JANINE" },
                "0": { name: "JANINE" },
                "1": { name: "JANINE" },
            }
        },
        "27": {
            name: "COOLTRAINER",
            class: "CooltrainerM",
            //image: "https://archives.bulbagarden.net/media/upload/3/3b/Spr_HGSS_Ace_Trainer_M.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Ace_Trainer_M.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Ace_Trainer_M.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "NICK" },
                "2": { name: "AARON" },
                "3": { name: "PAUL" },
                "4": { name: "CODY" },
                "5": { name: "MIKE" },
                "6": { name: "GAVEN" },
                "7": { name: "GAVEN" },
                "8": { name: "RYAN" },
                "9": { name: "JAKE" },
                "10": { name: "GAVEN" },
                "11": { name: "BLAKE" },
                "12": { name: "BRIAN" },
                "13": { name: "ERICK" },
                "14": { name: "ANDY" },
                "15": { name: "TYLER" },
                "16": { name: "SEAN" },
                "17": { name: "KEVIN" },
                "18": { name: "STEVE" },
                "19": { name: "ALLEN" },
                "20": { name: "DARIN" },
            }
        },
        "28": {
            name: "COOLTRAINER",
            class: "CooltrainerF",
            //image: "https://archives.bulbagarden.net/media/upload/8/86/Spr_HGSS_Ace_Trainer_F.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Ace_Trainer_F.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Ace_Trainer_F.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "GWEN" },
                "2": { name: "LOIS" },
                "3": { name: "FRAN" },
                "4": { name: "LOLA" },
                "5": { name: "KATE" },
                "6": { name: "IRENE" },
                "7": { name: "KELLY" },
                "8": { name: "JOYCE" },
                "9": { name: "BETH" },
                "10": { name: "REENA" },
                "11": { name: "MEGAN" },
                "12": { name: "BETH" },
                "13": { name: "CAROL" },
                "14": { name: "QUINN" },
                "15": { name: "EMMA" },
                "16": { name: "CYBIL" },
                "17": { name: "JENN" },
                "18": { name: "BETH" },
                "19": { name: "REENA" },
                "20": { name: "REENA" },
                "21": { name: "CARA" },
            }
        },
        "29": {
            name: "BEAUTY",
            class: "Beauty",
            //image: "https://archives.bulbagarden.net/media/upload/6/63/Spr_HGSS_Beauty.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Beauty.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Beauty.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "VICTORIA" },
                "2": { name: "SAMANTHA" },
                "3": { name: "JULIE" },
                "4": { name: "JACLYN" },
                "5": { name: "BRENDA" },
                "6": { name: "CASSIE" },
                "7": { name: "CAROLINE" },
                "8": { name: "CARLENE" },
                "9": { name: "JESSICA" },
                "10": { name: "RACHAEL" },
                "11": { name: "ANGELICA" },
                "12": { name: "KENDRA" },
                "13": { name: "VERONICA" },
                "14": { name: "JULIA" },
                "15": { name: "THERESA" },
                "16": { name: "VALERIE" },
                "17": { name: "OLIVIA" },
            }
        },
        "30": {
            name: "POK\xE9MANIAC",
            class: "Pokemaniac",
            //image: "https://archives.bulbagarden.net/media/upload/4/48/Spr_HGSS_Pok%C3%A9_Maniac.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Pok%C3%A9_Maniac.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Pok%C3%A9_Maniac.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "LARRY" },
                "2": { name: "ANDREW" },
                "3": { name: "CALVIN" },
                "4": { name: "SHANE" },
                "5": { name: "BEN" },
                "6": { name: "BRENT" },
                "7": { name: "RON" },
                "8": { name: "ETHAN" },
                "9": { name: "BRENT" },
                "10": { name: "BRENT" },
                "11": { name: "ISSAC" },
                "12": { name: "DONALD" },
                "13": { name: "ZACH" },
                "14": { name: "BRENT" },
                "15": { name: "MILLER" },
            }
        },
        "31": {
            name: "ROCKET",
            class: "GruntM",
            //image: "https://archives.bulbagarden.net/media/upload/d/d6/Spr_HGSS_Rocket_Grunt_M.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Rocket_Grunt_M.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Rocket_Grunt_M.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "GRUNT" },
                "2": { name: "GRUNT" },
                "3": { name: "GRUNT" },
                "4": { name: "GRUNT" },
                "5": { name: "GRUNT" },
                "6": { name: "GRUNT" },
                "7": { name: "GRUNT" },
                "8": { name: "GRUNT" },
                "9": { name: "GRUNT" },
                "10": { name: "GRUNT" },
                "11": { name: "GRUNT" },
                "12": { name: "EXECUTIVE" },
                "13": { name: "GRUNT" },
                "14": { name: "GRUNT" },
                "15": { name: "GRUNT" },
                "16": { name: "GRUNT" },
                "17": { name: "GRUNT" },
                "18": { name: "GRUNT" },
                "19": { name: "GRUNT" },
                "20": { name: "GRUNT" },
                "21": { name: "GRUNT" },
                "22": { name: "EXECUTIVE" },
                "23": { name: "EXECUTIVE" },
                "24": { name: "GRUNT" },
                "25": { name: "GRUNT" },
                "26": { name: "GRUNT" },
                "27": { name: "EXECUTIVE" },
                "28": { name: "GRUNT" },
                "29": { name: "GRUNT" },
                "30": { name: "GRUNT" },
                "31": { name: "GRUNT" },
            }
        },
        "32": {
            name: "GENTLEMAN",
            class: "Gentleman",
            //image: "https://archives.bulbagarden.net/media/upload/0/08/Spr_HGSS_Gentleman.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Gentleman.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Gentleman.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "PRESTON" },
                "2": { name: "EDWARD" },
                "3": { name: "GREGORY" },
                "4": { name: "VIRGIL" },
                "5": { name: "ALFRED" },
            }
        },
        "33": {
            name: "SKIER",
            class: "Skier",
            //image: "https://archives.bulbagarden.net/media/upload/4/41/Spr_HGSS_Skier.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Skier.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Skier.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "ROXANNE" },
                "2": { name: "CLARISSA" },
            }
        },
        "34": {
            name: "TEACHER",
            class: "Teacher",
            //image: "https://archives.bulbagarden.net/media/upload/a/ab/Spr_HGSS_Teacher.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Teacher.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Teacher.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "COLETTE" },
                "2": { name: "HILLARY" },
                "3": { name: "SHIRLEY" },
            }
        },
        "35": {
            name: "LEADER",
            class: "Sabrina",
            //image: "https://archives.bulbagarden.net/media/upload/archive/d/dc/20240316184858%21Spr_HGSS_Sabrina.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Sabrina.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Sabrina.png",
            teams: {
                "": { name: "SABRINA" },
                "0": { name: "SABRINA" },
                "1": { name: "SABRINA" },
            }
        },
        "36": {
            name: "BUG CATCHER",
            class: "BugCatcher",
            //image: "https://archives.bulbagarden.net/media/upload/4/45/Spr_HGSS_Bug_Catcher.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Bug_Catcher.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Bug_Catcher.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "DON" },
                "2": { name: "ROB" },
                "3": { name: "ED" },
                "4": { name: "WADE" },
                "5": { name: "BENNY" },
                "6": { name: "AL" },
                "7": { name: "JOSH" },
                "8": { name: "ARNIE" },
                "9": { name: "KEN" },
                "10": { name: "WADE" },
                "11": { name: "WADE" },
                "12": { name: "DOUG" },
                "13": { name: "ARNIE" },
                "14": { name: "ARNIE" },
                "15": { name: "WADE" },
                "16": { name: "WADE" },
                "17": { name: "ARNIE" },
                "18": { name: "ARNIE" },
                "19": { name: "WAYNE" },
            }
        },
        "37": {
            name: "FISHER",
            class: "Fisher",
            //image: "https://archives.bulbagarden.net/media/upload/c/c2/Spr_DP_Fisherman.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Fisherman.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Fisherman.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "JUSTIN" },
                "2": { name: "RALPH" },
                "3": { name: "ARNOLD" },
                "4": { name: "KYLE" },
                "5": { name: "HENRY" },
                "6": { name: "MARVIN" },
                "7": { name: "TULLY" },
                "8": { name: "ANDRE" },
                "9": { name: "RAYMOND" },
                "10": { name: "WILTON" },
                "11": { name: "EDGAR" },
                "12": { name: "JONAH" },
                "13": { name: "MARTIN" },
                "14": { name: "STEPHEN" },
                "15": { name: "BARNEY" },
                "16": { name: "RALPH" },
                "17": { name: "RALPH" },
                "18": { name: "TULLY" },
                "19": { name: "TULLY" },
                "20": { name: "WILTON" },
                "21": { name: "SCOTT" },
                "22": { name: "WILTON" },
                "23": { name: "RALPH" },
                "24": { name: "RALPH" },
                "25": { name: "TULLY" },
            }
        },
        "38": {
            name: "SWIMMER\u2642",
            class: "SwimmerM",
            //image: "https://archives.bulbagarden.net/media/upload/d/d7/Spr_HGSS_Swimmer_M_JP.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Swimmer_M_JP.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Swimmer_M_JP.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "HAROLD" },
                "2": { name: "SIMON" },
                "3": { name: "RANDALL" },
                "4": { name: "CHARLIE" },
                "5": { name: "GEORGE" },
                "6": { name: "BERKE" },
                "7": { name: "KIRK" },
                "8": { name: "MATHEW" },
                "9": { name: "HAL" },
                "10": { name: "PATON" },
                "11": { name: "DARYL" },
                "12": { name: "WALTER" },
                "13": { name: "TONY" },
                "14": { name: "JEROME" },
                "15": { name: "TUCKER" },
                "16": { name: "RICK" },
                "17": { name: "CAMERON" },
                "18": { name: "SETH" },
                "19": { name: "JAMES" },
                "20": { name: "LEWIS" },
                "21": { name: "PARKER" },
            }
        },
        "39": {
            name: "SWIMMER\u2640",
            class: "SwimmerF",
            //image: "https://archives.bulbagarden.net/media/upload/5/5f/Spr_HGSS_Swimmer_F.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Swimmer_F.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_FRLG_Swimmer_M.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "ELAINE" },
                "2": { name: "PAULA" },
                "3": { name: "KAYLEE" },
                "4": { name: "SUSIE" },
                "5": { name: "DENISE" },
                "6": { name: "KARA" },
                "7": { name: "WENDY" },
                "8": { name: "LISA" },
                "9": { name: "JILL" },
                "10": { name: "MARY" },
                "11": { name: "KATIE" },
                "12": { name: "DAWN" },
                "13": { name: "TARA" },
                "14": { name: "NICOLE" },
                "15": { name: "LORI" },
                "16": { name: "JODY" },
                "17": { name: "NIKKI" },
                "18": { name: "DIANA" },
                "19": { name: "BRIANA" },
            }
        },
        "40": {
            name: "SAILOR",
            class: "Sailor",
            //image: "https://archives.bulbagarden.net/media/upload/4/4e/Spr_DP_Sailor.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Sailor.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Sailor.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "EUGENE" },
                "2": { name: "HUEY" },
                "3": { name: "TERRELL" },
                "4": { name: "KENT" },
                "5": { name: "ERNEST" },
                "6": { name: "JEFF" },
                "7": { name: "GARRETT" },
                "8": { name: "KENNETH" },
                "9": { name: "STANLY" },
                "10": { name: "HARRY" },
                "11": { name: "HUEY" },
                "12": { name: "HUEY" },
                "13": { name: "HUEY" },
            }
        },
        "41": {
            name: "SUPER NERD",
            class: "SuperNerd",
            //image: "https://archives.bulbagarden.net/media/upload/3/3d/Spr_HGSS_Super_Nerd.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Super_Nerd.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Super_Nerd.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "STAN" },
                "2": { name: "ERIC" },
                "3": { name: "GREGG" },
                "4": { name: "JAY" },
                "5": { name: "DAVE" },
                "6": { name: "SAM" },
                "7": { name: "TOM" },
                "8": { name: "PAT" },
                "9": { name: "SHAWN" },
                "10": { name: "TERU" },
                "11": { name: "RUSS" },
                "12": { name: "NORTON" },
                "13": { name: "HUGH" },
                "14": { name: "MARKUS" },
            }
        },
        "42": {
            name: "RIVAL",
            class: "Rival2",
            //image: "https://archives.bulbagarden.net/media/upload/9/95/Spr_HGSS_Silver.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Silver.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Silver.png",
            teams: {
                "": { name: "***RivalName***" },
                "0": { name: "***RivalName***" },
                "1": { name: "***RivalName***" },
                "2": { name: "***RivalName***" },
                "3": { name: "***RivalName***" },
                "4": { name: "***RivalName***" },
                "5": { name: "***RivalName***" },
                "6": { name: "***RivalName***" },
            }
        },
        "43": {
            name: "GUITARIST",
            class: "Guitarist",
            //image: "https://archives.bulbagarden.net/media/upload/8/8c/Spr_DP_Guitarist.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Guitarist.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Guitarist.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "CLYDE" },
                "2": { name: "VINCENT" },
            }
        },
        "44": {
            name: "HIKER",
            class: "Hiker",
            //image: "https://archives.bulbagarden.net/media/upload/7/76/Spr_DP_Hiker.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Hiker.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Hiker.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "ANTHONY" },
                "2": { name: "RUSSELL" },
                "3": { name: "PHILLIP" },
                "4": { name: "LEONARD" },
                "5": { name: "ANTHONY" },
                "6": { name: "BENJAMIN" },
                "7": { name: "ERIK" },
                "8": { name: "MICHAEL" },
                "9": { name: "PARRY" },
                "10": { name: "TIMOTHY" },
                "11": { name: "BAILEY" },
                "12": { name: "ANTHONY" },
                "13": { name: "TIM" },
                "14": { name: "NOLAND" },
                "15": { name: "SIDNEY" },
                "16": { name: "KENNY" },
                "17": { name: "JIM" },
                "18": { name: "DANIEL" },
                "19": { name: "PARRY" },
                "20": { name: "PARRY" },
                "21": { name: "ANTHONY" },
                "22": { name: "ANTHONY" },
            }
        },
        "45": {
            name: "BIKER",
            class: "Biker",
            //image: "https://archives.bulbagarden.net/media/upload/4/4c/Spr_HGSS_Biker.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Biker.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Biker.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "BENNY" },
                "2": { name: "KAZU" },
                "3": { name: "DWAYNE" },
                "4": { name: "HARRIS" },
                "5": { name: "ZEKE" },
                "6": { name: "CHARLES" },
                "7": { name: "RILEY" },
                "8": { name: "JOEL" },
                "9": { name: "GLENN" },
            }
        },
        "46": {
            name: "LEADER",
            class: "Blaine",
            //image: "https://archives.bulbagarden.net/media/upload/7/78/Spr_HGSS_Blaine.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Blaine.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Blaine.png",
            teams: {
                "": { name: "BLAINE" },
                "0": { name: "BLAINE" },
                "1": { name: "BLAINE" },
            }
        },
        "47": {
            name: "BURGLAR",
            class: "Burglar",
            //image: "https://archives.bulbagarden.net/media/upload/5/5b/Spr_HGSS_Burglar.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Burglar.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Burglar.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "DUNCAN" },
                "2": { name: "EDDIE" },
                "3": { name: "COREY" },
            }
        },
        "48": {
            name: "FIREBREATHER",
            class: "FireBreather",
            //image: "https://archives.bulbagarden.net/media/upload/a/a7/Spr_HGSS_Firebreather.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Firebreather.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Firebreather.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "OTIS" },
                "2": { name: "DICK" },
                "3": { name: "NED" },
                "4": { name: "BURT" },
                "5": { name: "BILL" },
                "6": { name: "WALT" },
                "7": { name: "RAY" },
                "8": { name: "LYLE" },
            }
        },
        "49": {
            name: "JUGGLER",
            class: "Juggler",
            //image: "https://archives.bulbagarden.net/media/upload/e/e6/Spr_HGSS_Juggler.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Juggler.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Juggler.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "IRWIN" },
                "2": { name: "FRITZ" },
                "3": { name: "HORTON" },
                "4": { name: "IRWIN" },
                "5": { name: "IRWIN" },
                "6": { name: "IRWIN" },
            }
        },
        "50": {
            name: "BLACKBELT",
            class: "Blackbelt",
            //image: "https://archives.bulbagarden.net/media/upload/3/37/Spr_HGSS_Black_Belt.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Black_Belt.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Black_Belt.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "KENJI" },
                "2": { name: "YOSHI" },
                "3": { name: "KENJI" },
                "4": { name: "LAO" },
                "5": { name: "NOB" },
                "6": { name: "KIYO" },
                "7": { name: "LUNG" },
                "8": { name: "KENJI" },
                "9": { name: "WAI" },
            }
        },
        "51": {
            name: "ROCKET",
            class: "ExecutiveM",
            //image: "https://archives.bulbagarden.net/media/upload/9/96/Spr_HGSS_Petrel.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Petrel.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Petrel.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "EXECUTIVE" },
                "2": { name: "EXECUTIVE" },
                "3": { name: "EXECUTIVE" },
                "4": { name: "EXECUTIVE" },
            }
        },
        "52": {
            name: "PSYCHIC",
            class: "Psychic",
            //image: "https://archives.bulbagarden.net/media/upload/1/1f/Spr_DP_Psychic_M.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Psychic_M.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Psychic_M.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "NATHAN" },
                "2": { name: "FRANKLIN" },
                "3": { name: "HERMAN" },
                "4": { name: "FIDEL" },
                "5": { name: "GREG" },
                "6": { name: "NORMAN" },
                "7": { name: "MARK" },
                "8": { name: "PHIL" },
                "9": { name: "RICHARD" },
                "10": { name: "GILBERT" },
                "11": { name: "JARED" },
                "12": { name: "RODNEY" },
            }
        },
        "53": {
            name: "PICNICKER",
            class: "Picnicker",
            //image: "https://archives.bulbagarden.net/media/upload/d/dd/Spr_DP_Picnicker.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Picnicker.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Picnicker.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "LIZ" },
                "2": { name: "GINA" },
                "3": { name: "BROOKE" },
                "4": { name: "KIM" },
                "5": { name: "CINDY" },
                "6": { name: "HOPE" },
                "7": { name: "SHARON" },
                "8": { name: "DEBRA" },
                "9": { name: "GINA" },
                "10": { name: "ERIN" },
                "11": { name: "LIZ" },
                "12": { name: "LIZ" },
                "13": { name: "HEIDI" },
                "14": { name: "EDNA" },
                "15": { name: "GINA" },
                "16": { name: "TIFFANY" },
                "17": { name: "TIFFANY" },
                "18": { name: "ERIN" },
                "19": { name: "TANYA" },
                "20": { name: "TIFFANY" },
                "21": { name: "ERIN" },
                "22": { name: "LIZ" },
                "23": { name: "LIZ" },
                "24": { name: "GINA" },
                "25": { name: "GINA" },
                "26": { name: "TIFFANY" },
            }
        },
        "54": {
            name: "CAMPER",
            class: "Camper",
            //image: "https://archives.bulbagarden.net/media/upload/6/68/Spr_DP_Camper.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Camper.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Camper.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "ROLAND" },
                "2": { name: "TODD" },
                "3": { name: "IVAN" },
                "4": { name: "ELLIOT" },
                "5": { name: "BARRY" },
                "6": { name: "LLOYD" },
                "7": { name: "DEAN" },
                "8": { name: "SID" },
                "9": { name: "HARVEY" },
                "10": { name: "DALE" },
                "11": { name: "TED" },
                "12": { name: "TODD" },
                "13": { name: "TODD" },
                "14": { name: "THOMAS" },
                "15": { name: "LEROY" },
                "16": { name: "DAVID" },
                "17": { name: "JOHN" },
                "18": { name: "JERRY" },
                "19": { name: "SPENCER" },
                "20": { name: "TODD" },
                "21": { name: "TODD" },
                "22": { name: "QUENTIN" },
            }
        },
        "55": {
            name: "ROCKET",
            class: "ExecutiveF",
            //image: "https://archives.bulbagarden.net/media/upload/2/20/Spr_HGSS_Ariana.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Ariana.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Ariana.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "EXECUTIVE" },
                "2": { name: "EXECUTIVE" },
            }
        },
        "56": {
            name: "SAGE",
            class: "Sage",
            //image: "https://archives.bulbagarden.net/media/upload/0/07/Spr_HGSS_Sage.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Sage.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Sage.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "CHOW" },
                "2": { name: "NICO" },
                "3": { name: "JIN" },
                "4": { name: "TROY" },
                "5": { name: "JEFFREY" },
                "6": { name: "PING" },
                "7": { name: "EDMOND" },
                "8": { name: "NEAL" },
                "9": { name: "LI" },
                "10": { name: "GAKU" },
                "11": { name: "MASA" },
                "12": { name: "KOJI" },
            }
        },
        "57": {
            name: "MEDIUM",
            class: "Medium",
            //image: "https://archives.bulbagarden.net/media/upload/5/56/Spr_HGSS_Medium.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Medium.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Medium.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "MARTHA" },
                "2": { name: "GRACE" },
                "3": { name: "BETHANY" },
                "4": { name: "MARGRET" },
                "5": { name: "ETHEL" },
                "6": { name: "REBECCA" },
                "7": { name: "DORIS" },
            }
        },
        "58": {
            name: "BOARDER",
            class: "Boarder",
            //image: "https://archives.bulbagarden.net/media/upload/4/42/Spr_HGSS_Boarder.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Boarder.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Boarder.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "RONALD" },
                "2": { name: "BRAD" },
                "3": { name: "DOUGLAS" },
            }
        },
        "59": {
            name: "POK\xE9FAN",
            class: "PokefanM",
            //image: "https://archives.bulbagarden.net/media/upload/8/87/Spr_DP_Pok%C3%A9fan_M.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Pok%C3%A9fan_M.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Pok%C3%A9fan_M.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "WILLIAM" },
                "2": { name: "DEREK" },
                "3": { name: "ROBERT" },
                "4": { name: "JOSHUA" },
                "5": { name: "CARTER" },
                "6": { name: "TREVOR" },
                "7": { name: "BRANDON" },
                "8": { name: "JEREMY" },
                "9": { name: "COLIN" },
                "10": { name: "DEREK" },
                "11": { name: "DEREK" },
                "12": { name: "ALEX" },
                "13": { name: "REX" },
                "14": { name: "ALLAN" },
            }
        },
        "60": {
            name: "KIMONO GIRL",
            class: "KimonoGirl",
            //image: "https://archives.bulbagarden.net/media/upload/0/01/Spr_HGSS_Kimono_Girl.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Kimono_Girl.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Kimono_Girl.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "NAOKO" },
                "2": { name: "NAOKO" },
                "3": { name: "SAYO" },
                "4": { name: "ZUKI" },
                "5": { name: "KUNI" },
                "6": { name: "MIKI" },
            }
        },
        "61": {
            name: "TWINS",
            class: "Twins",
            //image: "https://archives.bulbagarden.net/media/upload/f/f8/Spr_HGSS_Twins.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Twins.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Twins.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "AMY AND MAY" },
                "2": { name: "ANN AND ANNE" },
                "3": { name: "ANN AND ANNE" },
                "4": { name: "AMY AND MAY" },
                "5": { name: "JO AND ZOE" },
                "6": { name: "JO AND ZOE" },
                "7": { name: "MEG AND PEG" },
                "8": { name: "MEG AND PEG" },
                "9": { name: "LEA AND PIA" },
                "10": { name: "LEA AND PIA" },
            }
        },
        "62": {
            name: "POK\xE9FAN",
            class: "PokefanF",
            //image: "https://archives.bulbagarden.net/media/upload/c/c2/Spr_DP_Pok%C3%A9fan_F.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Pok%C3%A9fan_F.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Pok%C3%A9fan_F.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "BEVERLY" },
                "2": { name: "RUTH" },
                "3": { name: "BEVERLY" },
                "4": { name: "BEVERLY" },
                "5": { name: "GEORGIA" },
                "6": { name: "JAIME" },
            }
        },
        "63": {
            name: "PKMN TRAINER",
            class: "Red",
            //image: "https://archives.bulbagarden.net/media/upload/e/e8/Spr_HGSS_Red.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Red.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Red.png",
            teams: {
                "": { name: "RED" },
                "0": { name: "RED" },
                "1": { name: "RED" },
            }
        },
        "64": {
            name: "LEADER",
            class: "Blue",
            //image: "https://archives.bulbagarden.net/media/upload/f/fd/Spr_HGSS_Blue.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Blue.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Blue.png",
            teams: {
                "": { name: "BLUE" },
                "0": { name: "BLUE" },
                "1": { name: "BLUE" },
            }
        },
        "65": {
            name: "OFFICER",
            class: "Officer",
            //image: "https://archives.bulbagarden.net/media/upload/0/0d/Spr_DP_Officer.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_DP_Officer.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_DP_Officer.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "KEITH" },
                "2": { name: "DIRK" },
            }
        },
        "66": {
            name: "ROCKET",
            class: "GruntF",
            //image: "https://archives.bulbagarden.net/media/upload/c/cd/Spr_HGSS_Rocket_Grunt_F.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Rocket_Grunt_F.png",
            reference: "https://archives.bulbagarden.net/wiki/File:Spr_HGSS_Rocket_Grunt_F.png",
            teams: {
                "": { name: "" },
                "0": { name: "" },
                "1": { name: "GRUNT" },
                "2": { name: "GRUNT" },
                "3": { name: "GRUNT" },
                "4": { name: "GRUNT" },
                "5": { name: "GRUNT" },
            }
        },
        "67": {
            name: "MYSTICALMAN",
            class: "Mysticalman",
            //image: "https://archives.bulbagarden.net/media/upload/4/4a/Spr_HGSS_Eusine.png",
            image: "https://static.merkelhaus.us/overlayimages/trainers/Spr_HGSS_Eusine.png",
            reference: "https://bulbapedia.bulbagarden.net/wiki/File:Spr_HGSS_Eusine.png",
            teams: {
                "": { name: "EUSINE" },
                "0": { name: "EUSINE" },
                "1": { name: "EUSINE" },
            }
        },
    };

    private trainersLookupTeamsEntries: { [key: string | number]: ITrainer } = objMap(this.trainersLookupKV, (k, v) => { return k === "teams" ? new Map<string | number, ITrainerTeam>(Object.entries(v as object).map(([key, value]) => [NumberOrString(key), value])) : v; }, (k, v) => { return k !== "teams"; });
    private trainersLookupTeamsMap: [string | number, ITrainer][] = Object.entries(this.trainersLookupTeamsEntries).map(([key, value]) => [NumberOrString(key), value]);
    public trainersLookup: Map<string | number, ITrainer> = new Map<string | number, ITrainer>(this.trainersLookupTeamsMap);
};

export default TrainersLookup;

