import * as typeStyles from '../../Types.module';
import ITypeLookup from '../Interfaces/ITypeLookup'
import { NumberOrString } from 'Util'
import IType from '../Interfaces/IType'

export class TypeLookup implements ITypeLookup {
    private typeLookupKV: { [key: string | number]: IType } = {
        0x00: { name: "Normal", old_css_class: typeStyles.normal_type_old, new_css_class: typeStyles.normal_type_new },
        0x01: { name: "Fighting", old_css_class: typeStyles.fighting_type_old, new_css_class: typeStyles.fighting_type_new },
        0x02: { name: "Flying", old_css_class: typeStyles.flying_type_old, new_css_class: typeStyles.flying_type_new },
        0x03: { name: "Poison", old_css_class: typeStyles.poison_type_old, new_css_class: typeStyles.poison_type_new },
        0x04: { name: "Ground", old_css_class: typeStyles.ground_type_old, new_css_class: typeStyles.ground_type_new },
        0x05: { name: "Rock", old_css_class: typeStyles.rock_type_old, new_css_class: typeStyles.rock_type_new },
        0x06: { name: "BIRD", old_css_class: typeStyles.bird_type_old, new_css_class: typeStyles.bird_type_new },
        0x07: { name: "Bug", old_css_class: typeStyles.bug_type_old, new_css_class: typeStyles.bug_type_new },
        0x08: { name: "Ghost", old_css_class: typeStyles.ghost_type_old, new_css_class: typeStyles.ghost_type_new },
        0x09: { name: "Steel", old_css_class: typeStyles.steel_type_old, new_css_class: typeStyles.steel_type_new },
        0x0A: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0B: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0C: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0D: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0E: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0F: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x10: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x11: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x12: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x13: { name: "???", old_css_class: typeStyles.questionquestionquestion_type_old, new_css_class: typeStyles.questionquestionquestion_type_new },
        0x14: { name: "Fire", old_css_class: typeStyles.fire_type_old, new_css_class: typeStyles.fire_type_new },
        0x15: { name: "Water", old_css_class: typeStyles.water_type_old, new_css_class: typeStyles.water_type_new },
        0x16: { name: "Grass", old_css_class: typeStyles.grass_type_old, new_css_class: typeStyles.grass_type_new },
        0x17: { name: "Electric", old_css_class: typeStyles.electric_type_old, new_css_class: typeStyles.electric_type_new },
        0x18: { name: "Psychic", old_css_class: typeStyles.psychic_type_old, new_css_class: typeStyles.psychic_type_new },
        0x19: { name: "Ice", old_css_class: typeStyles.ice_type_old, new_css_class: typeStyles.ice_type_new },
        0x1A: { name: "Dragon", old_css_class: typeStyles.dragon_type_old, new_css_class: typeStyles.dragon_type_new },
        0x1B: { name: "Dark", old_css_class: typeStyles.dark_type_old, new_css_class: typeStyles.dark_type_new },
        0x1C: { name: "\u0102?99\u010299", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1D: { name: "9??99??9?99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1E: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1F: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x20: { name: "Y EHCD299Z\u0102", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x21: { name: "9Q9Q Q 99\u20BD\u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x22: { name: "??99??99???", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x23: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x24: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x25: { name: "9II99e??99I", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x26: { name: "9C9??99\u0102BBH", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x27: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x28: { name: "9? 99IIIII9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x29: { name: " 99 \xDC\xDC<pokemon name>", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2A: { name: "'l\xE9    ( \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2B: { name: "EEEEEEEEEEE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2C: { name: "\xF6'm", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2D: { name: "9Q9QQQQ9||?", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2E: { name: "\u01029\u01022I6  99<trainer name>", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2F: { name: "?9??99?'99?", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x30: { name: "???9?A99A:\xD6", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x31: { name: "??9J 99lK99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x32: { name: "??99??99\u0102'9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x33: { name: "9999999!", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x34: { name: "_99'm 99<\u30699", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x35: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x36: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x37: { name: "Q Q 99Q Q 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x38: { name: "]99II9II99I", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x39: { name: "\u3069\u2640 f", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3A: { name: "v9l 99l'm99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3B: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3C: { name: "9QQQQ|| ||99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3D: { name: "\u3069\u2640 f", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3E: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3F: { name: "f", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x40: { name: "9J99||99KK9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x41: { name: "9Z?999!9\u255D_9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x42: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x43: { name: "k9't699", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x44: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x45: { name: "4I'l\xE9Hi", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x46: { name: "9QQQQQ9QQQQ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x47: { name: "69AAQqAAA 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x48: { name: "9\u20BD9\u20BDq'996POK\xE99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x49: { name: "\u010299 <player name>HHHONM", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4A: { name: "9???99??", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4B: { name: "???99\u0102\u0102??\u0102\u0102", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4C: { name: "Q99\u20BDQ\u20BD99Q\u20BDQ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4D: { name: "999I||99IB 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4E: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4F: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x50: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x51: { name: "999999!", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x52: { name: "9???99\u0102\u0102??\u0102\u0102", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x53: { name: "'l\xE9HI   ( \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x54: { name: "99\xE4999Z999 ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x55: { name: "9II??99I9II", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x56: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x57: { name: "aPkMnfPkMnkPkMn....", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x58: { name: "RID'dBN? wPkx", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x59: { name: "[\xF6  9\xE9(\xF6\xE9[\xF6", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5A: { name: "4w'sJ\xE9 's\u20BD ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5B: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5C: { name: "'s?M FFFFFF", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5D: { name: "\xDC_[", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5E: { name: "_yF\u2518????FRx", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5F: { name: "w\xC4 48 h\u20BD;\u2640 ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x60: { name: "TO<player name> _Erz\xFC'|", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x61: { name: "TRAINER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x62: { name: "???????????", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x63: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x64: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x65: { name: "(((((((((((", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x66: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x67: { name: "(((((((((((", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x68: { name: "(((((((((((", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x69: { name: ")))))))))(\u20BDk", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6A: { name: "((((((((((\u20BDk", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6B: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6C: { name: "<pokemon name>(_  ?C<pokemon name>c?'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6D: { name: "CA?A?g AES:", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6E: { name: "9'|9'|9'|9'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6F: { name: "DDF_", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x70: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x71: { name: "EEDHHHHHHHH", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x72: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x73: { name: "<pokemon name>(_  ?C<pokemon name>c?'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x74: { name: "???????????", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x75: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x76: { name: "???????????", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x77: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x78: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x79: { name: "<pokemon name>(_  ?C<pokemon name>c?'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7A: { name: "CJQXw      ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7B: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7C: { name: "ROCKETFDCDDD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7D: { name: "???????????", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7E: { name: "????????9T ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7F: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x80: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x81: { name: "FIGHTING", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x82: { name: "FLYING", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x83: { name: "POISON", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x84: { name: "GROUND", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x85: { name: "ROCK", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x86: { name: "BIRD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x87: { name: "BUG", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x88: { name: "GHOST", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x89: { name: "STEEL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8A: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8B: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8C: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8D: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8E: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8F: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x90: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x91: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x92: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x93: { name: "???", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x94: { name: "FIRE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x95: { name: "WATER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x96: { name: "GRASS", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x97: { name: "ELECTRIC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x98: { name: "PSYCHIC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x99: { name: "ICE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9A: { name: "DRAGON", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9B: { name: "DARK", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9C: { name: "\u0102?99\u010299", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9D: { name: "9??99??9?99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9E: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9F: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA0: { name: "Y EHCD299Z\u0102", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA1: { name: "9Q9Q Q 99\u20BD\u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA2: { name: "??99??99???", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA3: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA4: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA5: { name: "9II99e??99I", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA6: { name: "9C9??99\u0102BBH", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA7: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA8: { name: "9? 99IIIII9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA9: { name: " 99 \xDC\xDC<pokemon name>", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAA: { name: "'l\xE9    ( \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAB: { name: "EEEEEEEEEEE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAC: { name: "\xF6'm", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAD: { name: "9Q9QQQQ9||?", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAE: { name: "\u01029\u01022I6  99<trainer name>", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAF: { name: "?9??99?'99?", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB0: { name: "???9?A99A:\xD6", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB1: { name: "??9J 99lK99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB2: { name: "??99??99\u0102'9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB3: { name: "9999999!", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB4: { name: "_99'm 99<\u30699", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB5: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB6: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB7: { name: "Q Q 99Q Q 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB8: { name: "]99II9II99I", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB9: { name: "\u3069\u2640 f", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBA: { name: "v9l 99l'm99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBB: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBC: { name: "9QQQQ|| ||99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBD: { name: "\u3069\u2640 f", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBE: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBF: { name: "f", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC0: { name: "9J99||99KK9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC1: { name: "9Z?999!9\u255D_9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC2: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC3: { name: "k9't699", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC4: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC5: { name: "4I'l\xE9Hi", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC6: { name: "9QQQQQ9QQQQ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC7: { name: "69AAQqAAA 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC8: { name: "9\u20BD9\u20BDq'996POK\xE99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC9: { name: "\u010299 <player name>HHHONM", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCA: { name: "9???99??", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCB: { name: "???99\u0102\u0102??\u0102\u0102", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCC: { name: "Q99\u20BDQ\u20BD99Q\u20BDQ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCD: { name: "999I||99IB 99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCE: { name: "(freeze)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCF: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD0: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD1: { name: "999999!", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD2: { name: "9???99\u0102\u0102??\u0102\u0102", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD3: { name: "'l\xE9HI   ( \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD4: { name: "99\xE4999Z999 ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD5: { name: "9II??99I9II", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD6: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD7: { name: "aPkMnfPkMnkPkMn....", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD8: { name: "RID'dBN? wPkx", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD9: { name: "[\xF6  9\xE9(\xF6\xE9[\xF6", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDA: { name: "4w'sJ\xE9 's\u20BD ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDB: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDC: { name: "'s?M FFFFFF", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDD: { name: "\xDC_[", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDE: { name: "_yF\u2518????FRx", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDF: { name: "w\xC4 48 h\u20BD;\u2640 ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE0: { name: "TO<player name> _Erz\xFC'|", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE1: { name: "TRAINER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE2: { name: "???????????", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE3: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE4: { name: "(crash)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE5: { name: "(((((((((((", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE6: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE7: { name: "(((((((((((", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE8: { name: "(((((((((((", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE9: { name: ")))))))))(Pk", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEA: { name: "((((((((((Pk", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEB: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEC: { name: "<pokemon name>(_  ?C<pokemon name>c?'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xED: { name: "CA?A?g AES:", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEE: { name: "9'|9'|9'|9'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEF: { name: "DDF_", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF0: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF1: { name: "EEDHHHHHHHH", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF2: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF3: { name: "<pokemon name>(_  ?C<pokemon name>c?'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF4: { name: "???????????", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF5: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF6: { name: "???????????", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF7: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF8: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF9: { name: "<pokemon name>(_  ?C<pokemon name>c?'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFA: { name: "CJQXw      ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFB: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFC: { name: "ROCKETFDCDDD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFD: { name: "???????????", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFE: { name: "????????9T ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFF: { name: "?C..m?? _\u20BDF\u2518", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
    };

    private keyValuePairs: [string | number, IType][] = Object.entries(this.typeLookupKV).map(([key, value]) => [NumberOrString(key), value]);
    public typeLookup: Map<string | number, IType> = new Map<string | number, IType>(this.keyValuePairs);
};

export default TypeLookup;
