export class TypeLookup {
	private static typeLookupKV = {
		0x00: { name: "Normal", css_class: "normal-type" },
		0x01: { name: "Fighting", css_class: "fighting-type" },
		0x02: { name: "Flying", css_class: "flying-type" },
		0x03: { name: "Poison", css_class: "poison-type" },
		0x04: { name: "Ground", css_class: "ground-type" },
		0x05: { name: "Rock", css_class: "rock-type" },
		0x06: { name: "BIRD", css_class: "bird-type" },
		0x07: { name: "Bug", css_class: "bug-type" },
		0x08: { name: "Ghost", css_class: "ghost-type" },
		0x09: { name: "Steel", css_class: "steel-type" },
		0x0A: { name: "NORMAL", css_class: "fake-type" },
		0x0B: { name: "NORMAL", css_class: "fake-type" },
		0x0C: { name: "NORMAL", css_class: "fake-type" },
		0x0D: { name: "NORMAL", css_class: "fake-type" },
		0x0E: { name: "NORMAL", css_class: "fake-type" },
		0x0F: { name: "NORMAL", css_class: "fake-type" },
		0x10: { name: "NORMAL", css_class: "fake-type" },
		0x11: { name: "NORMAL", css_class: "fake-type" },
		0x12: { name: "NORMAL", css_class: "fake-type" },
		0x13: { name: "???", css_class: "questionquestionquestion-type" },
		0x14: { name: "Fire", css_class: "fire-type" },
		0x15: { name: "Water", css_class: "water-type" },
		0x16: { name: "Grass", css_class: "grass-type" },
		0x17: { name: "Electric", css_class: "electric-type" },
		0x18: { name: "Psychic", css_class: "psychic-type" },
		0x19: { name: "Ice", css_class: "ice-type" },
		0x1A: { name: "Dragon", css_class: "dragon-type" },
		0x1B: { name: "Dark", css_class: "dark-type" },
		0x1C: { name: "\u0102?99\u010299", css_class: "fake-type" },
		0x1D: { name: "9??99??9?99", css_class: "fake-type" },
		0x1E: { name: "(freeze)", css_class: "fake-type" },
		0x1F: { name: "(freeze)", css_class: "fake-type" },
		0x20: { name: "Y EHCD299Z\u0102", css_class: "fake-type" },
		0x21: { name: "9Q9Q Q 99\u20BD\u20BD", css_class: "fake-type" },
		0x22: { name: "??99??99???", css_class: "fake-type" },
		0x23: { name: "(blank)", css_class: "fake-type" },
		0x24: { name: "(crash)", css_class: "fake-type" },
		0x25: { name: "9II99e??99I", css_class: "fake-type" },
		0x26: { name: "9C9??99\u0102BBH", css_class: "fake-type" },
		0x27: { name: "(crash)", css_class: "fake-type" },
		0x28: { name: "9? 99IIIII9", css_class: "fake-type" },
		0x29: { name: " 99 \xDC\xDC<pokemon name>", css_class: "fake-type" },
		0x2A: { name: "'l\xE9    ( \u20BD", css_class: "fake-type" },
		0x2B: { name: "EEEEEEEEEEE", css_class: "fake-type" },
		0x2C: { name: "\xF6'm", css_class: "fake-type" },
		0x2D: { name: "9Q9QQQQ9||?", css_class: "fake-type" },
		0x2E: { name: "\u01029\u01022I6  99<trainer name>", css_class: "fake-type" },
		0x2F: { name: "?9??99?'99?", css_class: "fake-type" },
		0x30: { name: "???9?A99A:\xD6", css_class: "fake-type" },
		0x31: { name: "??9J 99lK99", css_class: "fake-type" },
		0x32: { name: "??99??99\u0102'9", css_class: "fake-type" },
		0x33: { name: "9999999!", css_class: "fake-type" },
		0x34: { name: "_99'm 99<\u30699", css_class: "fake-type" },
		0x35: { name: "(crash)", css_class: "fake-type" },
		0x36: { name: "(crash)", css_class: "fake-type" },
		0x37: { name: "Q Q 99Q Q 9", css_class: "fake-type" },
		0x38: { name: "]99II9II99I", css_class: "fake-type" },
		0x39: { name: "\u3069\u2640 f", css_class: "fake-type" },
		0x3A: { name: "v9l 99l'm99", css_class: "fake-type" },
		0x3B: { name: "(freeze)", css_class: "fake-type" },
		0x3C: { name: "9QQQQ|| ||99", css_class: "fake-type" },
		0x3D: { name: "\u3069\u2640 f", css_class: "fake-type" },
		0x3E: { name: "(freeze)", css_class: "fake-type" },
		0x3F: { name: "f", css_class: "fake-type" },
		0x40: { name: "9J99||99KK9", css_class: "fake-type" },
		0x41: { name: "9Z?999!9\u255D_9", css_class: "fake-type" },
		0x42: { name: "(crash)", css_class: "fake-type" },
		0x43: { name: "k9't699", css_class: "fake-type" },
		0x44: { name: "(freeze)", css_class: "fake-type" },
		0x45: { name: "4I'l\xE9Hi", css_class: "fake-type" },
		0x46: { name: "9QQQQQ9QQQQ", css_class: "fake-type" },
		0x47: { name: "69AAQqAAA 9", css_class: "fake-type" },
		0x48: { name: "9\u20BD9\u20BDq'996POK\xE99", css_class: "fake-type" },
		0x49: { name: "\u010299 <player name>HHHONM", css_class: "fake-type" },
		0x4A: { name: "9???99??", css_class: "fake-type" },
		0x4B: { name: "???99\u0102\u0102??\u0102\u0102", css_class: "fake-type" },
		0x4C: { name: "Q99\u20BDQ\u20BD99Q\u20BDQ", css_class: "fake-type" },
		0x4D: { name: "999I||99IB 99", css_class: "fake-type" },
		0x4E: { name: "(freeze)", css_class: "fake-type" },
		0x4F: { name: "(crash)", css_class: "fake-type" },
		0x50: { name: "(crash)", css_class: "fake-type" },
		0x51: { name: "999999!", css_class: "fake-type" },
		0x52: { name: "9???99\u0102\u0102??\u0102\u0102", css_class: "fake-type" },
		0x53: { name: "'l\xE9HI   ( \u20BD", css_class: "fake-type" },
		0x54: { name: "99\xE4999Z999 ", css_class: "fake-type" },
		0x55: { name: "9II??99I9II", css_class: "fake-type" },
		0x56: { name: "(blank)", css_class: "fake-type" },
		0x57: { name: "aPkMnfPkMnkPkMn....", css_class: "fake-type" },
		0x58: { name: "RID'dBN? wPkx", css_class: "fake-type" },
		0x59: { name: "[\xF6  9\xE9(\xF6\xE9[\xF6", css_class: "fake-type" },
		0x5A: { name: "4w'sJ\xE9 's\u20BD ", css_class: "fake-type" },
		0x5B: { name: "(blank)", css_class: "fake-type" },
		0x5C: { name: "'s?M FFFFFF", css_class: "fake-type" },
		0x5D: { name: "\xDC_[", css_class: "fake-type" },
		0x5E: { name: "_yF\u2518????FRx", css_class: "fake-type" },
		0x5F: { name: "w\xC4 48 h\u20BD;\u2640 ", css_class: "fake-type" },
		0x60: { name: "TO<player name> _Erz\xFC'|", css_class: "fake-type" },
		0x61: { name: "TRAINER", css_class: "fake-type" },
		0x62: { name: "???????????", css_class: "fake-type" },
		0x63: { name: "(crash)", css_class: "fake-type" },
		0x64: { name: "(crash)", css_class: "fake-type" },
		0x65: { name: "(((((((((((", css_class: "fake-type" },
		0x66: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0x67: { name: "(((((((((((", css_class: "fake-type" },
		0x68: { name: "(((((((((((", css_class: "fake-type" },
		0x69: { name: ")))))))))(\u20BDk", css_class: "fake-type" },
		0x6A: { name: "((((((((((\u20BDk", css_class: "fake-type" },
		0x6B: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0x6C: { name: "<pokemon name>(_  ?C<pokemon name>c?'", css_class: "fake-type" },
		0x6D: { name: "CA?A?g AES:", css_class: "fake-type" },
		0x6E: { name: "9'|9'|9'|9'", css_class: "fake-type" },
		0x6F: { name: "DDF_", css_class: "fake-type" },
		0x70: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0x71: { name: "EEDHHHHHHHH", css_class: "fake-type" },
		0x72: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0x73: { name: "<pokemon name>(_  ?C<pokemon name>c?'", css_class: "fake-type" },
		0x74: { name: "???????????", css_class: "fake-type" },
		0x75: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0x76: { name: "???????????", css_class: "fake-type" },
		0x77: { name: "(blank)", css_class: "fake-type" },
		0x78: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0x79: { name: "<pokemon name>(_  ?C<pokemon name>c?'", css_class: "fake-type" },
		0x7A: { name: "CJQXw      ", css_class: "fake-type" },
		0x7B: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0x7C: { name: "ROCKETFDCDDD", css_class: "fake-type" },
		0x7D: { name: "???????????", css_class: "fake-type" },
		0x7E: { name: "????????9T ", css_class: "fake-type" },
		0x7F: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0x80: { name: "NORMAL", css_class: "fake-type" },
		0x81: { name: "FIGHTING", css_class: "fake-type" },
		0x82: { name: "FLYING", css_class: "fake-type" },
		0x83: { name: "POISON", css_class: "fake-type" },
		0x84: { name: "GROUND", css_class: "fake-type" },
		0x85: { name: "ROCK", css_class: "fake-type" },
		0x86: { name: "BIRD", css_class: "fake-type" },
		0x87: { name: "BUG", css_class: "fake-type" },
		0x88: { name: "GHOST", css_class: "fake-type" },
		0x89: { name: "STEEL", css_class: "fake-type" },
		0x8A: { name: "NORMAL", css_class: "fake-type" },
		0x8B: { name: "NORMAL", css_class: "fake-type" },
		0x8C: { name: "NORMAL", css_class: "fake-type" },
		0x8D: { name: "NORMAL", css_class: "fake-type" },
		0x8E: { name: "NORMAL", css_class: "fake-type" },
		0x8F: { name: "NORMAL", css_class: "fake-type" },
		0x90: { name: "NORMAL", css_class: "fake-type" },
		0x91: { name: "NORMAL", css_class: "fake-type" },
		0x92: { name: "NORMAL", css_class: "fake-type" },
		0x93: { name: "???", css_class: "fake-type" },
		0x94: { name: "FIRE", css_class: "fake-type" },
		0x95: { name: "WATER", css_class: "fake-type" },
		0x96: { name: "GRASS", css_class: "fake-type" },
		0x97: { name: "ELECTRIC", css_class: "fake-type" },
		0x98: { name: "PSYCHIC", css_class: "fake-type" },
		0x99: { name: "ICE", css_class: "fake-type" },
		0x9A: { name: "DRAGON", css_class: "fake-type" },
		0x9B: { name: "DARK", css_class: "fake-type" },
		0x9C: { name: "\u0102?99\u010299", css_class: "fake-type" },
		0x9D: { name: "9??99??9?99", css_class: "fake-type" },
		0x9E: { name: "(freeze)", css_class: "fake-type" },
		0x9F: { name: "(freeze)", css_class: "fake-type" },
		0xA0: { name: "Y EHCD299Z\u0102", css_class: "fake-type" },
		0xA1: { name: "9Q9Q Q 99\u20BD\u20BD", css_class: "fake-type" },
		0xA2: { name: "??99??99???", css_class: "fake-type" },
		0xA3: { name: "(blank)", css_class: "fake-type" },
		0xA4: { name: "(crash)", css_class: "fake-type" },
		0xA5: { name: "9II99e??99I", css_class: "fake-type" },
		0xA6: { name: "9C9??99\u0102BBH", css_class: "fake-type" },
		0xA7: { name: "(crash)", css_class: "fake-type" },
		0xA8: { name: "9? 99IIIII9", css_class: "fake-type" },
		0xA9: { name: " 99 \xDC\xDC<pokemon name>", css_class: "fake-type" },
		0xAA: { name: "'l\xE9    ( \u20BD", css_class: "fake-type" },
		0xAB: { name: "EEEEEEEEEEE", css_class: "fake-type" },
		0xAC: { name: "\xF6'm", css_class: "fake-type" },
		0xAD: { name: "9Q9QQQQ9||?", css_class: "fake-type" },
		0xAE: { name: "\u01029\u01022I6  99<trainer name>", css_class: "fake-type" },
		0xAF: { name: "?9??99?'99?", css_class: "fake-type" },
		0xB0: { name: "???9?A99A:\xD6", css_class: "fake-type" },
		0xB1: { name: "??9J 99lK99", css_class: "fake-type" },
		0xB2: { name: "??99??99\u0102'9", css_class: "fake-type" },
		0xB3: { name: "9999999!", css_class: "fake-type" },
		0xB4: { name: "_99'm 99<\u30699", css_class: "fake-type" },
		0xB5: { name: "(crash)", css_class: "fake-type" },
		0xB6: { name: "(crash)", css_class: "fake-type" },
		0xB7: { name: "Q Q 99Q Q 9", css_class: "fake-type" },
		0xB8: { name: "]99II9II99I", css_class: "fake-type" },
		0xB9: { name: "\u3069\u2640 f", css_class: "fake-type" },
		0xBA: { name: "v9l 99l'm99", css_class: "fake-type" },
		0xBB: { name: "(freeze)", css_class: "fake-type" },
		0xBC: { name: "9QQQQ|| ||99", css_class: "fake-type" },
		0xBD: { name: "\u3069\u2640 f", css_class: "fake-type" },
		0xBE: { name: "(freeze)", css_class: "fake-type" },
		0xBF: { name: "f", css_class: "fake-type" },
		0xC0: { name: "9J99||99KK9", css_class: "fake-type" },
		0xC1: { name: "9Z?999!9\u255D_9", css_class: "fake-type" },
		0xC2: { name: "(crash)", css_class: "fake-type" },
		0xC3: { name: "k9't699", css_class: "fake-type" },
		0xC4: { name: "(freeze)", css_class: "fake-type" },
		0xC5: { name: "4I'l\xE9Hi", css_class: "fake-type" },
		0xC6: { name: "9QQQQQ9QQQQ", css_class: "fake-type" },
		0xC7: { name: "69AAQqAAA 9", css_class: "fake-type" },
		0xC8: { name: "9\u20BD9\u20BDq'996POK\xE99", css_class: "fake-type" },
		0xC9: { name: "\u010299 <player name>HHHONM", css_class: "fake-type" },
		0xCA: { name: "9???99??", css_class: "fake-type" },
		0xCB: { name: "???99\u0102\u0102??\u0102\u0102", css_class: "fake-type" },
		0xCC: { name: "Q99\u20BDQ\u20BD99Q\u20BDQ", css_class: "fake-type" },
		0xCD: { name: "999I||99IB 99", css_class: "fake-type" },
		0xCE: { name: "(freeze)", css_class: "fake-type" },
		0xCF: { name: "(crash)", css_class: "fake-type" },
		0xD0: { name: "(crash)", css_class: "fake-type" },
		0xD1: { name: "999999!", css_class: "fake-type" },
		0xD2: { name: "9???99\u0102\u0102??\u0102\u0102", css_class: "fake-type" },
		0xD3: { name: "'l\xE9HI   ( \u20BD", css_class: "fake-type" },
		0xD4: { name: "99\xE4999Z999 ", css_class: "fake-type" },
		0xD5: { name: "9II??99I9II", css_class: "fake-type" },
		0xD6: { name: "(blank)", css_class: "fake-type" },
		0xD7: { name: "aPkMnfPkMnkPkMn....", css_class: "fake-type" },
		0xD8: { name: "RID'dBN? wPkx", css_class: "fake-type" },
		0xD9: { name: "[\xF6  9\xE9(\xF6\xE9[\xF6", css_class: "fake-type" },
		0xDA: { name: "4w'sJ\xE9 's\u20BD ", css_class: "fake-type" },
		0xDB: { name: "(blank)", css_class: "fake-type" },
		0xDC: { name: "'s?M FFFFFF", css_class: "fake-type" },
		0xDD: { name: "\xDC_[", css_class: "fake-type" },
		0xDE: { name: "_yF\u2518????FRx", css_class: "fake-type" },
		0xDF: { name: "w\xC4 48 h\u20BD;\u2640 ", css_class: "fake-type" },
		0xE0: { name: "TO<player name> _Erz\xFC'|", css_class: "fake-type" },
		0xE1: { name: "TRAINER", css_class: "fake-type" },
		0xE2: { name: "???????????", css_class: "fake-type" },
		0xE3: { name: "(crash)", css_class: "fake-type" },
		0xE4: { name: "(crash)", css_class: "fake-type" },
		0xE5: { name: "(((((((((((", css_class: "fake-type" },
		0xE6: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0xE7: { name: "(((((((((((", css_class: "fake-type" },
		0xE8: { name: "(((((((((((", css_class: "fake-type" },
		0xE9: { name: ")))))))))(Pk", css_class: "fake-type" },
		0xEA: { name: "((((((((((Pk", css_class: "fake-type" },
		0xEB: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0xEC: { name: "<pokemon name>(_  ?C<pokemon name>c?'", css_class: "fake-type" },
		0xED: { name: "CA?A?g AES:", css_class: "fake-type" },
		0xEE: { name: "9'|9'|9'|9'", css_class: "fake-type" },
		0xEF: { name: "DDF_", css_class: "fake-type" },
		0xF0: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0xF1: { name: "EEDHHHHHHHH", css_class: "fake-type" },
		0xF2: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0xF3: { name: "<pokemon name>(_  ?C<pokemon name>c?'", css_class: "fake-type" },
		0xF4: { name: "???????????", css_class: "fake-type" },
		0xF5: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0xF6: { name: "???????????", css_class: "fake-type" },
		0xF7: { name: "(blank)", css_class: "fake-type" },
		0xF8: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0xF9: { name: "<pokemon name>(_  ?C<pokemon name>c?'", css_class: "fake-type" },
		0xFA: { name: "CJQXw      ", css_class: "fake-type" },
		0xFB: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
		0xFC: { name: "ROCKETFDCDDD", css_class: "fake-type" },
		0xFD: { name: "???????????", css_class: "fake-type" },
		0xFE: { name: "????????9T ", css_class: "fake-type" },
		0xFF: { name: "?C..m?? _\u20BDF\u2518", css_class: "fake-type" },
	};

	private static keyValuePairs = Object.entries(this.typeLookupKV);
	public static typeLookup = new Map(this.keyValuePairs);
};

export default TypeLookup;