import * as typeStyles from '../../Types.module';
import ITypeLookup from '../Interfaces/ITypeLookup'
import { NumberOrString } from 'Util'
import IType from '../Interfaces/IType'

export class TypeLookup implements ITypeLookup {
    private typeLookupKV: { [key: string | number]: IType } = {
        0x00: { name: "Normal", old_css_class: typeStyles.normal_type_old, new_css_class: typeStyles.normal_type_new },
        0x01: { name: "Fighting", old_css_class: typeStyles.fighting_type_old, new_css_class: typeStyles.fighting_type_new },
        0x02: { name: "Flying", old_css_class: typeStyles.flying_type_old, new_css_class: typeStyles.flying_type_new },
        0x03: { name: "Poison", old_css_class: typeStyles.poison_type_old, new_css_class: typeStyles.poison_type_new },
        0x04: { name: "Ground", old_css_class: typeStyles.ground_type_old, new_css_class: typeStyles.ground_type_new },
        0x05: { name: "Rock", old_css_class: typeStyles.rock_type_old, new_css_class: typeStyles.rock_type_new },
        0x06: { name: "BIRD", old_css_class: typeStyles.bird_type_old, new_css_class: typeStyles.bird_type_new },
        0x07: { name: "Bug", old_css_class: typeStyles.bug_type_old, new_css_class: typeStyles.bug_type_new },
        0x08: { name: "Ghost", old_css_class: typeStyles.ghost_type_old, new_css_class: typeStyles.ghost_type_new },
        0x09: { name: "Steel", old_css_class: typeStyles.steel_type_old, new_css_class: typeStyles.steel_type_new },
        0x0A: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0B: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0C: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0D: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0E: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x0F: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x10: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x11: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x12: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x13: { name: "???", old_css_class: typeStyles.questionquestionquestion_type_old, new_css_class: typeStyles.questionquestionquestion_type_new },
        0x14: { name: "Fire", old_css_class: typeStyles.fire_type_old, new_css_class: typeStyles.fire_type_new },
        0x15: { name: "Water", old_css_class: typeStyles.water_type_old, new_css_class: typeStyles.water_type_new },
        0x16: { name: "Grass", old_css_class: typeStyles.grass_type_old, new_css_class: typeStyles.grass_type_new },
        0x17: { name: "Electric", old_css_class: typeStyles.electric_type_old, new_css_class: typeStyles.electric_type_new },
        0x18: { name: "Psychic", old_css_class: typeStyles.psychic_type_old, new_css_class: typeStyles.psychic_type_new },
        0x19: { name: "Ice", old_css_class: typeStyles.ice_type_old, new_css_class: typeStyles.ice_type_new },
        0x1A: { name: "Dragon", old_css_class: typeStyles.dragon_type_old, new_css_class: typeStyles.dragon_type_new },
        0x1B: { name: "Dark", old_css_class: typeStyles.dark_type_old, new_css_class: typeStyles.dark_type_new },
        0x1C: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1D: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1E: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x1F: { name: "\u01029q9Y 99 69", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x20: { name: "9 9 89", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x21: { name: "9  99Q 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x22: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x23: { name: "'l4.", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x24: { name: "9    9 E", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x25: { name: "9I9I9\u30699", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x26: { name: "9 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x27: { name: "ED 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x28: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x29: { name: "_99_9\xDC9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2A: { name: "x\u04D2r\u255D_ BB9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2B: { name: "  ||''999", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2C: { name: "3G EEN\xF6GB r", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2D: { name: "QQQQQ9Q||", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2E: { name: "989 9M9y 9||", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x2F: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x30: { name: "  99Q 9  99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x31: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x32: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x33: { name: "9          9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x34: { name: "9 9'm9 99\u30699", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x35: { name: "9    9    8", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x36: { name: "9q 88;[A 89", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x37: { name: "  99Q 9  99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x38: { name: "9IIII9I9  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x39: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3A: { name: "v9\u255D9_9\u255D99 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3B: { name: "998989   88", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3C: { name: "9QQQ9||9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3D: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3E: { name: "8899999  MM", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x3F: { name: "(\xD6'|4.", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x40: { name: "9J99|9K9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x41: { name: "9Z", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x42: { name: "9     \u20BD    ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x43: { name: " 96 899  89", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x44: { name: "9          ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x45: { name: "8C x\xC4r\u255D_  B", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x46: { name: "9QQQQ9QQ  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x47: { name: "     9    6", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x48: { name: " \xC4    6    ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x49: { name: "9   9   696", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4A: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4B: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4C: { name: "Q9Q\u20BD9\u20BD9\u20BD  \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4D: { name: "9I9I9I 9  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4E: { name: "9 9M9y29  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x4F: { name: "    9    E9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x50: { name: "9'9\u20BD9229  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x51: { name: " B    !     ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x52: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x53: { name: "x\xC4r\u255D_  B  B", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x54: { name: "999999Z9  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x55: { name: "9II9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x56: { name: "       G  8", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x57: { name: "'rPkMn..Pk.. PkMn\xF6", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x58: { name: "  )[ tzx  t", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x59: { name: "           ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5A: { name: "   G  TM  C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5B: { name: "Q'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5C: { name: "TRAINER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5D: { name: "\xF6 \u255DPkMn", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5E: { name: "UVV9U", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x5F: { name: "f ?H8", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x60: { name: " \xE8       .", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x61: { name: "R_         ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x62: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x63: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x64: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x65: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x66: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x67: { name: "           ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x68: { name: "E E EE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x69: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6A: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6B: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6C: { name: "3\u20BD _", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6D: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6E: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x6F: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x70: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x71: { name: "\xE8\xE8 4.   E \xE8", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x72: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x73: { name: "3\u20BD _", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x74: { name: "  A'C     [", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x75: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x76: { name: "\u20BD.   't\xFCr \xDC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x77: { name: "CKET", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x78: { name: " B         \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x79: { name: "3\u20BD _", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7A: { name: "  yXRE L   ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7B: { name: " B        \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7C: { name: "'l) m) ZM", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7D: { name: "U ST ST   T", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7E: { name: "'d\xE8['d\xE8k'd\xE8w'dR", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x7F: { name: " B        \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x80: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x81: { name: "FIGHTING", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x82: { name: "FLYING", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x83: { name: "POISON", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x84: { name: "GROUND", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x85: { name: "ROCK", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x86: { name: "BIRD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x87: { name: "BUG", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x88: { name: "GHOST", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x89: { name: "STEEL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8A: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8B: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8C: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8D: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8E: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x8F: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x90: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x91: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x92: { name: "NORMAL", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x93: { name: "???", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x94: { name: "FIRE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x95: { name: "WATER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x96: { name: "GRASS", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x97: { name: "ELECTRIC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x98: { name: "PSYCHIC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x99: { name: "ICE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9A: { name: "DRAGON", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9B: { name: "DARK", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9C: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9D: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9E: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0x9F: { name: "\u01029q9Y 99 69", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA0: { name: "9 9 89", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA1: { name: "9  99Q 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA2: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA3: { name: "'l4.", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA4: { name: "9    9 E", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA5: { name: "9I9I9\u30699", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA6: { name: "9 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA7: { name: "ED 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA8: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xA9: { name: "_99_9\xDC9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAA: { name: "x\u04D2r\u255D_ BB9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAB: { name: "  ||''999", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAC: { name: "3G EEN\xF6GB r", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAD: { name: "QQQQQ9Q||", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAE: { name: "989 9M9y 9||", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xAF: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB0: { name: "  99Q 9  99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB1: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB2: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB3: { name: "9          9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB4: { name: "9 9'm9 99\u30699", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB5: { name: "9    9    8", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB6: { name: "9q 88;[A 89", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB7: { name: "  99Q 9  99", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB8: { name: "9IIII9I9  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xB9: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBA: { name: "v9\u255D9_9\u255D99 9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBB: { name: "998989   88", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBC: { name: "9QQQ9||9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBD: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBE: { name: "8899999  MM", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xBF: { name: "(\xD6'|4.", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC0: { name: "9J99|9K9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC1: { name: "9Z", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC2: { name: "9     \u20BD    ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC3: { name: " 96 899  89", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC4: { name: "9          ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC5: { name: "8C x\xC4r\u255D_  B", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC6: { name: "9QQQQ9QQ  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC7: { name: "     9    6", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC8: { name: " \xC4    6    ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xC9: { name: "9   9   696", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCA: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCB: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCC: { name: "Q9Q\u20BD9\u20BD9\u20BD  \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCD: { name: "9I9I9I 9  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCE: { name: "9 9M9y29  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xCF: { name: "    9    E9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD0: { name: "9'9\u20BD9229  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD1: { name: " B    !     ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD2: { name: "9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD3: { name: "x\xC4r\u255D_  B  B", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD4: { name: "999999Z9  9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD5: { name: "9II9", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD6: { name: "       G  8", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD7: { name: "'rPkMn..Pk.. PkMn\xF6", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD8: { name: "  )[ tzx  t", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xD9: { name: "           ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDA: { name: "   G  TM  C", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDB: { name: "Q'", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDC: { name: "TRAINER", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDD: { name: "\xF6 \u255DPkMn", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDE: { name: "UVV9U", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xDF: { name: "f ?H8", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE0: { name: " \xE8       .", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE1: { name: "R_         ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE2: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE3: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE4: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE5: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE6: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE7: { name: "           ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE8: { name: "E E EE", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xE9: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEA: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEB: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEC: { name: "3\u20BD _", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xED: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEE: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xEF: { name: "(blank)", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF0: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF1: { name: "\xE8\xE8 4.   E \xE8", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF2: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF3: { name: "3\u20BD _", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF4: { name: "  A'C     [", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF5: { name: "  B        ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF6: { name: "\u20BD.   't\xFCr \xDC", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF7: { name: "CKET", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF8: { name: " B         \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xF9: { name: "3\u20BD _", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFA: { name: "  yXRE L   ", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFB: { name: " B        \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFC: { name: "'l) m) ZM", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFD: { name: "U ST ST   T", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFE: { name: "'d\xE8['d\xE8k'd\xE8w'dR", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
        0xFF: { name: " B        \u20BD", old_css_class: typeStyles.fake_type_old, new_css_class: typeStyles.fake_type_new },
    };

    private keyValuePairs: [string | number, IType][] = Object.entries(this.typeLookupKV).map(([key, value]) => [NumberOrString(key), value]);
    public typeLookup: Map<string | number, IType> = new Map<string | number, IType>(this.keyValuePairs);
};

export default TypeLookup;
