export class TypeLookup {
	private static typeLookupKV = {
		0x00: { name: "Normal", css_class: "normal-type" },
		0x01: { name: "Fighting", css_class: "fighting-type" },
		0x02: { name: "Flying", css_class: "flying-type" },
		0x03: { name: "Poison", css_class: "poison-type" },
		0x04: { name: "Ground", css_class: "ground-type" },
		0x05: { name: "Rock", css_class: "rock-type" },
		0x06: { name: "BIRD", css_class: "bird-type" },
		0x07: { name: "Bug", css_class: "bug-type" },
		0x08: { name: "Ghost", css_class: "ghost-type" },
		0x09: { name: "Steel", css_class: "steel-type" },
		0x0A: { name: "NORMAL", css_class: "fake-type" },
		0x0B: { name: "NORMAL", css_class: "fake-type" },
		0x0C: { name: "NORMAL", css_class: "fake-type" },
		0x0D: { name: "NORMAL", css_class: "fake-type" },
		0x0E: { name: "NORMAL", css_class: "fake-type" },
		0x0F: { name: "NORMAL", css_class: "fake-type" },
		0x10: { name: "NORMAL", css_class: "fake-type" },
		0x11: { name: "NORMAL", css_class: "fake-type" },
		0x12: { name: "NORMAL", css_class: "fake-type" },
		0x13: { name: "???", css_class: "questionquestionquestion-type" },
		0x14: { name: "Fire", css_class: "fire-type" },
		0x15: { name: "Water", css_class: "water-type" },
		0x16: { name: "Grass", css_class: "grass-type" },
		0x17: { name: "Electric", css_class: "electric-type" },
		0x18: { name: "Psychic", css_class: "psychic-type" },
		0x19: { name: "Ice", css_class: "ice-type" },
		0x1A: { name: "Dragon", css_class: "dragon-type" },
		0x1B: { name: "Dark", css_class: "dark-type" },
		0x1C: { name: "9", css_class: "fake-type" },
		0x1D: { name: "9", css_class: "fake-type" },
		0x1E: { name: "9", css_class: "fake-type" },
		0x1F: { name: "\u01029q9Y 99 69", css_class: "fake-type" },
		0x20: { name: "9 9 89", css_class: "fake-type" },
		0x21: { name: "9  99Q 9", css_class: "fake-type" },
		0x22: { name: "9", css_class: "fake-type" },
		0x23: { name: "'l4.", css_class: "fake-type" },
		0x24: { name: "9    9 E", css_class: "fake-type" },
		0x25: { name: "9I9I9\u30699", css_class: "fake-type" },
		0x26: { name: "9 9", css_class: "fake-type" },
		0x27: { name: "ED 9", css_class: "fake-type" },
		0x28: { name: "(blank)", css_class: "fake-type" },
		0x29: { name: "_99_9\xDC9", css_class: "fake-type" },
		0x2A: { name: "x\u04D2r\u255D_ BB9", css_class: "fake-type" },
		0x2B: { name: "  ||''999", css_class: "fake-type" },
		0x2C: { name: "3G EEN\xF6GB r", css_class: "fake-type" },
		0x2D: { name: "QQQQQ9Q||", css_class: "fake-type" },
		0x2E: { name: "989 9M9y 9||", css_class: "fake-type" },
		0x2F: { name: "9", css_class: "fake-type" },
		0x30: { name: "  99Q 9  99", css_class: "fake-type" },
		0x31: { name: "9", css_class: "fake-type" },
		0x32: { name: "9", css_class: "fake-type" },
		0x33: { name: "9          9", css_class: "fake-type" },
		0x34: { name: "9 9'm9 99\u30699", css_class: "fake-type" },
		0x35: { name: "9    9    8", css_class: "fake-type" },
		0x36: { name: "9q 88;[A 89", css_class: "fake-type" },
		0x37: { name: "  99Q 9  99", css_class: "fake-type" },
		0x38: { name: "9IIII9I9  9", css_class: "fake-type" },
		0x39: { name: "(blank)", css_class: "fake-type" },
		0x3A: { name: "v9\u255D9_9\u255D99 9", css_class: "fake-type" },
		0x3B: { name: "998989   88", css_class: "fake-type" },
		0x3C: { name: "9QQQ9||9", css_class: "fake-type" },
		0x3D: { name: "(blank)", css_class: "fake-type" },
		0x3E: { name: "8899999  MM", css_class: "fake-type" },
		0x3F: { name: "(\xD6'|4.", css_class: "fake-type" },
		0x40: { name: "9J99|9K9", css_class: "fake-type" },
		0x41: { name: "9Z", css_class: "fake-type" },
		0x42: { name: "9     \u20BD    ", css_class: "fake-type" },
		0x43: { name: " 96 899  89", css_class: "fake-type" },
		0x44: { name: "9          ", css_class: "fake-type" },
		0x45: { name: "8C x\xC4r\u255D_  B", css_class: "fake-type" },
		0x46: { name: "9QQQQ9QQ  9", css_class: "fake-type" },
		0x47: { name: "     9    6", css_class: "fake-type" },
		0x48: { name: " \xC4    6    ", css_class: "fake-type" },
		0x49: { name: "9   9   696", css_class: "fake-type" },
		0x4A: { name: "(blank)", css_class: "fake-type" },
		0x4B: { name: "9", css_class: "fake-type" },
		0x4C: { name: "Q9Q\u20BD9\u20BD9\u20BD  \u20BD", css_class: "fake-type" },
		0x4D: { name: "9I9I9I 9  9", css_class: "fake-type" },
		0x4E: { name: "9 9M9y29  9", css_class: "fake-type" },
		0x4F: { name: "    9    E9", css_class: "fake-type" },
		0x50: { name: "9'9\u20BD9229  9", css_class: "fake-type" },
		0x51: { name: " B    !     ", css_class: "fake-type" },
		0x52: { name: "9", css_class: "fake-type" },
		0x53: { name: "x\xC4r\u255D_  B  B", css_class: "fake-type" },
		0x54: { name: "999999Z9  9", css_class: "fake-type" },
		0x55: { name: "9II9", css_class: "fake-type" },
		0x56: { name: "       G  8", css_class: "fake-type" },
		0x57: { name: "'rPkMn..Pk.. PkMn\xF6", css_class: "fake-type" },
		0x58: { name: "  )[ tzx  t", css_class: "fake-type" },
		0x59: { name: "           ", css_class: "fake-type" },
		0x5A: { name: "   G  TM  C", css_class: "fake-type" },
		0x5B: { name: "Q'", css_class: "fake-type" },
		0x5C: { name: "TRAINER", css_class: "fake-type" },
		0x5D: { name: "\xF6 \u255DPkMn", css_class: "fake-type" },
		0x5E: { name: "UVV9U", css_class: "fake-type" },
		0x5F: { name: "f ?H8", css_class: "fake-type" },
		0x60: { name: " \xE8       .", css_class: "fake-type" },
		0x61: { name: "R_         ", css_class: "fake-type" },
		0x62: { name: "(blank)", css_class: "fake-type" },
		0x63: { name: "(blank)", css_class: "fake-type" },
		0x64: { name: "(blank)", css_class: "fake-type" },
		0x65: { name: "(blank)", css_class: "fake-type" },
		0x66: { name: "  B        ", css_class: "fake-type" },
		0x67: { name: "           ", css_class: "fake-type" },
		0x68: { name: "E E EE", css_class: "fake-type" },
		0x69: { name: "(blank)", css_class: "fake-type" },
		0x6A: { name: "(blank)", css_class: "fake-type" },
		0x6B: { name: "  B        ", css_class: "fake-type" },
		0x6C: { name: "3\u20BD _", css_class: "fake-type" },
		0x6D: { name: "(blank)", css_class: "fake-type" },
		0x6E: { name: "(blank)", css_class: "fake-type" },
		0x6F: { name: "(blank)", css_class: "fake-type" },
		0x70: { name: "  B        ", css_class: "fake-type" },
		0x71: { name: "\xE8\xE8 4.   E \xE8", css_class: "fake-type" },
		0x72: { name: "  B        ", css_class: "fake-type" },
		0x73: { name: "3\u20BD _", css_class: "fake-type" },
		0x74: { name: "  A'C     [", css_class: "fake-type" },
		0x75: { name: "  B        ", css_class: "fake-type" },
		0x76: { name: "\u20BD.   't\xFCr \xDC", css_class: "fake-type" },
		0x77: { name: "CKET", css_class: "fake-type" },
		0x78: { name: " B         \u20BD", css_class: "fake-type" },
		0x79: { name: "3\u20BD _", css_class: "fake-type" },
		0x7A: { name: "  yXRE L   ", css_class: "fake-type" },
		0x7B: { name: " B        \u20BD", css_class: "fake-type" },
		0x7C: { name: "'l) m) ZM", css_class: "fake-type" },
		0x7D: { name: "U ST ST   T", css_class: "fake-type" },
		0x7E: { name: "'d\xE8['d\xE8k'd\xE8w'dR", css_class: "fake-type" },
		0x7F: { name: " B        \u20BD", css_class: "fake-type" },
		0x80: { name: "NORMAL", css_class: "fake-type" },
		0x81: { name: "FIGHTING", css_class: "fake-type" },
		0x82: { name: "FLYING", css_class: "fake-type" },
		0x83: { name: "POISON", css_class: "fake-type" },
		0x84: { name: "GROUND", css_class: "fake-type" },
		0x85: { name: "ROCK", css_class: "fake-type" },
		0x86: { name: "BIRD", css_class: "fake-type" },
		0x87: { name: "BUG", css_class: "fake-type" },
		0x88: { name: "GHOST", css_class: "fake-type" },
		0x89: { name: "STEEL", css_class: "fake-type" },
		0x8A: { name: "NORMAL", css_class: "fake-type" },
		0x8B: { name: "NORMAL", css_class: "fake-type" },
		0x8C: { name: "NORMAL", css_class: "fake-type" },
		0x8D: { name: "NORMAL", css_class: "fake-type" },
		0x8E: { name: "NORMAL", css_class: "fake-type" },
		0x8F: { name: "NORMAL", css_class: "fake-type" },
		0x90: { name: "NORMAL", css_class: "fake-type" },
		0x91: { name: "NORMAL", css_class: "fake-type" },
		0x92: { name: "NORMAL", css_class: "fake-type" },
		0x93: { name: "???", css_class: "fake-type" },
		0x94: { name: "FIRE", css_class: "fake-type" },
		0x95: { name: "WATER", css_class: "fake-type" },
		0x96: { name: "GRASS", css_class: "fake-type" },
		0x97: { name: "ELECTRIC", css_class: "fake-type" },
		0x98: { name: "PSYCHIC", css_class: "fake-type" },
		0x99: { name: "ICE", css_class: "fake-type" },
		0x9A: { name: "DRAGON", css_class: "fake-type" },
		0x9B: { name: "DARK", css_class: "fake-type" },
		0x9C: { name: "9", css_class: "fake-type" },
		0x9D: { name: "9", css_class: "fake-type" },
		0x9E: { name: "9", css_class: "fake-type" },
		0x9F: { name: "\u01029q9Y 99 69", css_class: "fake-type" },
		0xA0: { name: "9 9 89", css_class: "fake-type" },
		0xA1: { name: "9  99Q 9", css_class: "fake-type" },
		0xA2: { name: "9", css_class: "fake-type" },
		0xA3: { name: "'l4.", css_class: "fake-type" },
		0xA4: { name: "9    9 E", css_class: "fake-type" },
		0xA5: { name: "9I9I9\u30699", css_class: "fake-type" },
		0xA6: { name: "9 9", css_class: "fake-type" },
		0xA7: { name: "ED 9", css_class: "fake-type" },
		0xA8: { name: "(blank)", css_class: "fake-type" },
		0xA9: { name: "_99_9\xDC9", css_class: "fake-type" },
		0xAA: { name: "x\u04D2r\u255D_ BB9", css_class: "fake-type" },
		0xAB: { name: "  ||''999", css_class: "fake-type" },
		0xAC: { name: "3G EEN\xF6GB r", css_class: "fake-type" },
		0xAD: { name: "QQQQQ9Q||", css_class: "fake-type" },
		0xAE: { name: "989 9M9y 9||", css_class: "fake-type" },
		0xAF: { name: "9", css_class: "fake-type" },
		0xB0: { name: "  99Q 9  99", css_class: "fake-type" },
		0xB1: { name: "9", css_class: "fake-type" },
		0xB2: { name: "9", css_class: "fake-type" },
		0xB3: { name: "9          9", css_class: "fake-type" },
		0xB4: { name: "9 9'm9 99\u30699", css_class: "fake-type" },
		0xB5: { name: "9    9    8", css_class: "fake-type" },
		0xB6: { name: "9q 88;[A 89", css_class: "fake-type" },
		0xB7: { name: "  99Q 9  99", css_class: "fake-type" },
		0xB8: { name: "9IIII9I9  9", css_class: "fake-type" },
		0xB9: { name: "(blank)", css_class: "fake-type" },
		0xBA: { name: "v9\u255D9_9\u255D99 9", css_class: "fake-type" },
		0xBB: { name: "998989   88", css_class: "fake-type" },
		0xBC: { name: "9QQQ9||9", css_class: "fake-type" },
		0xBD: { name: "(blank)", css_class: "fake-type" },
		0xBE: { name: "8899999  MM", css_class: "fake-type" },
		0xBF: { name: "(\xD6'|4.", css_class: "fake-type" },
		0xC0: { name: "9J99|9K9", css_class: "fake-type" },
		0xC1: { name: "9Z", css_class: "fake-type" },
		0xC2: { name: "9     \u20BD    ", css_class: "fake-type" },
		0xC3: { name: " 96 899  89", css_class: "fake-type" },
		0xC4: { name: "9          ", css_class: "fake-type" },
		0xC5: { name: "8C x\xC4r\u255D_  B", css_class: "fake-type" },
		0xC6: { name: "9QQQQ9QQ  9", css_class: "fake-type" },
		0xC7: { name: "     9    6", css_class: "fake-type" },
		0xC8: { name: " \xC4    6    ", css_class: "fake-type" },
		0xC9: { name: "9   9   696", css_class: "fake-type" },
		0xCA: { name: "(blank)", css_class: "fake-type" },
		0xCB: { name: "9", css_class: "fake-type" },
		0xCC: { name: "Q9Q\u20BD9\u20BD9\u20BD  \u20BD", css_class: "fake-type" },
		0xCD: { name: "9I9I9I 9  9", css_class: "fake-type" },
		0xCE: { name: "9 9M9y29  9", css_class: "fake-type" },
		0xCF: { name: "    9    E9", css_class: "fake-type" },
		0xD0: { name: "9'9\u20BD9229  9", css_class: "fake-type" },
		0xD1: { name: " B    !     ", css_class: "fake-type" },
		0xD2: { name: "9", css_class: "fake-type" },
		0xD3: { name: "x\xC4r\u255D_  B  B", css_class: "fake-type" },
		0xD4: { name: "999999Z9  9", css_class: "fake-type" },
		0xD5: { name: "9II9", css_class: "fake-type" },
		0xD6: { name: "       G  8", css_class: "fake-type" },
		0xD7: { name: "'rPkMn..Pk.. PkMn\xF6", css_class: "fake-type" },
		0xD8: { name: "  )[ tzx  t", css_class: "fake-type" },
		0xD9: { name: "           ", css_class: "fake-type" },
		0xDA: { name: "   G  TM  C", css_class: "fake-type" },
		0xDB: { name: "Q'", css_class: "fake-type" },
		0xDC: { name: "TRAINER", css_class: "fake-type" },
		0xDD: { name: "\xF6 \u255DPkMn", css_class: "fake-type" },
		0xDE: { name: "UVV9U", css_class: "fake-type" },
		0xDF: { name: "f ?H8", css_class: "fake-type" },
		0xE0: { name: " \xE8       .", css_class: "fake-type" },
		0xE1: { name: "R_         ", css_class: "fake-type" },
		0xE2: { name: "(blank)", css_class: "fake-type" },
		0xE3: { name: "(blank)", css_class: "fake-type" },
		0xE4: { name: "(blank)", css_class: "fake-type" },
		0xE5: { name: "(blank)", css_class: "fake-type" },
		0xE6: { name: "  B        ", css_class: "fake-type" },
		0xE7: { name: "           ", css_class: "fake-type" },
		0xE8: { name: "E E EE", css_class: "fake-type" },
		0xE9: { name: "(blank)", css_class: "fake-type" },
		0xEA: { name: "(blank)", css_class: "fake-type" },
		0xEB: { name: "  B        ", css_class: "fake-type" },
		0xEC: { name: "3\u20BD _", css_class: "fake-type" },
		0xED: { name: "(blank)", css_class: "fake-type" },
		0xEE: { name: "(blank)", css_class: "fake-type" },
		0xEF: { name: "(blank)", css_class: "fake-type" },
		0xF0: { name: "  B        ", css_class: "fake-type" },
		0xF1: { name: "\xE8\xE8 4.   E \xE8", css_class: "fake-type" },
		0xF2: { name: "  B        ", css_class: "fake-type" },
		0xF3: { name: "3\u20BD _", css_class: "fake-type" },
		0xF4: { name: "  A'C     [", css_class: "fake-type" },
		0xF5: { name: "  B        ", css_class: "fake-type" },
		0xF6: { name: "\u20BD.   't\xFCr \xDC", css_class: "fake-type" },
		0xF7: { name: "CKET", css_class: "fake-type" },
		0xF8: { name: " B         \u20BD", css_class: "fake-type" },
		0xF9: { name: "3\u20BD _", css_class: "fake-type" },
		0xFA: { name: "  yXRE L   ", css_class: "fake-type" },
		0xFB: { name: " B        \u20BD", css_class: "fake-type" },
		0xFC: { name: "'l) m) ZM", css_class: "fake-type" },
		0xFD: { name: "U ST ST   T", css_class: "fake-type" },
		0xFE: { name: "'d\xE8['d\xE8k'd\xE8w'dR", css_class: "fake-type" },
		0xFF: { name: " B        \u20BD", css_class: "fake-type" },
	};

	private static keyValuePairs = Object.entries(this.typeLookupKV);
	public static typeLookup = new Map(this.keyValuePairs);
};

export default TypeLookup;
